"use strict";
(function(window,document){
const COLLECTION="registerDefinitions";
const CATALOG={
  "cpgrams-grievances":["registrationNo","dateReceived","complainantName","atrStatusView","finalStatusView","appealStatusView"],
  "cpgrams-appeals":["appealNumber","appealReceivedDate","appellantName","registrationNo","appealStatusView"],
  "cpgrams-other":["registrationNo","dateReceived","complainantName","subject","district","mandal","village","atrStatusView","finalStatusView","appealStatusView"],
  "cpgrams-questions":["questionNo","questionType","questionReceivedDate","questionConcernedSection","question","answer","answerFurnishedBy","answerFurnishedTo","answerFurnishedDate","questionCommunicationType","questionFileNumber","questionCommunicationDate","questionFileStatus","attachments"],
  "rti-applications":["applicationNumber","applicationDate","dueDate","daysStatus","applicantName","subject","concernedSection","replyStatusView","replySentStatus","workflowStage","finalStatusView","appealStatusView"],
  "disha-meetings":["district","dateOfMeeting","pomUploaded","pomPendingDays","statusOfBills","remarks"],
  "disha-pending-files":["district","officeFileNo","officeStatus","dateOfMeeting","remarks"]
};
const EXTRA={
  "cpgrams-grievances":["subject","category","district","mandal","village","dueDate","daysStatus","communicationStatusView","memoStatus","approvalStatusView","portalUploadStatus","replyGovtStatus","replyComplainantStatus","workflowStage","attachments"],
  "cpgrams-appeals":["appealDate","appealAuthority","appealCommunicationNo","appealDisposalDate","appealRemarks","complainantName","dateReceived","finalStatusView"],
  "cpgrams-other":["category","dueDate","daysStatus","communicationStatusView","memoStatus","approvalStatusView","portalUploadStatus","replyGovtStatus","replyComplainantStatus","workflowStage","attachments"],
  "cpgrams-questions":["district","mandal","village","finalStatusView"],
  "rti-applications":["mobileNumber","applicantAddress","district","mandal","village","officeFileNo","officeDateArised","officeSubject","officeCommunicationType","officeLetterAddressedTo","officeStatus","sentToSectionDate","assignedOfficer","firstAppealNumber","firstAppealDate","firstAppealStatus","secondAppealNumber","secondAppealDate","secondAppealStatus"],
  "disha-meetings":["pomUploadDate","meetingExpenditure","billsSubmittedCRD","billsForwardedMoRD","proposedDateOfMeeting","statusOfMeeting","officeFileNo","officeDateArised","officeSubject","officeCommunicationType","officeLetterAddressedTo","officeStatus"],
  "disha-pending-files":["statusOfMeeting","proposedDateOfMeeting","pomUploaded","pomPendingDays","officeDateArised","officeSubject","officeLetterAddressedTo"]
};
const LABELS={
 registrationNo:"Grievance No.",dateReceived:"Date Received",complainantName:"Complainant Name",atrStatusView:"ATR Status",finalStatusView:"Grievance Status",appealStatusView:"Appeal Status",appealNumber:"Appeal No.",appealReceivedDate:"Date Received",appellantName:"Appellant Name",appealDate:"Appeal Date",appealAuthority:"Appeal Authority",appealCommunicationNo:"Communication No.",appealDisposalDate:"Disposal Date",appealRemarks:"Appeal Remarks",subject:"Subject",category:"Category",district:"District",mandal:"Mandal",village:"Village",dueDate:"Due Date",daysStatus:"Days Left / Overdue Days",communicationStatusView:"Communication Status",memoStatus:"Memo Status",approvalStatusView:"Approval Status",portalUploadStatus:"Portal Upload Status",replyGovtStatus:"Reply to Government",replyComplainantStatus:"Reply to Complainant",workflowStage:"Workflow Stage",attachments:"Upload Document",questionNo:"LAQ / LCQ No.",questionType:"Question Type",questionReceivedDate:"Received Date",questionConcernedSection:"Concerned Section",question:"Question",answer:"Answer",answerFurnishedBy:"Answer Furnished By",answerFurnishedTo:"Answer Furnished To",answerFurnishedDate:"Answer Date",questionCommunicationType:"Communication Type",questionFileNumber:"File No.",questionCommunicationDate:"Communication Date",questionFileStatus:"File Status",applicationNumber:"RTI Application No.",applicationDate:"Application Date",applicantName:"Applicant Name",concernedSection:"Concerned Section",replyStatusView:"Reply Status",replySentStatus:"Reply Sent Status",firstAppealNumber:"First Appeal No.",firstAppealDate:"First Appeal Date",firstAppealStatus:"First Appeal Status",secondAppealNumber:"Second Appeal No.",secondAppealDate:"Second Appeal Date",secondAppealStatus:"Second Appeal Status",dateOfMeeting:"Meeting Date",pomUploaded:"PoM Uploaded",pomPendingDays:"PoM Pending Days",pomUploadDate:"PoM Upload Date",statusOfBills:"Bills Status",meetingExpenditure:"Meeting Expenditure",billsSubmittedCRD:"Bills Submitted to CRD",billsForwardedMoRD:"Bills Forwarded to MoRD",proposedDateOfMeeting:"Proposed Meeting Date",statusOfMeeting:"Meeting Status",remarks:"Remarks",officeFileNo:"File No.",officeStatus:"File Status",officeDateArised:"Date Arised",officeSubject:"Office Subject",officeCommunicationType:"Communication Type",officeLetterAddressedTo:"Addressed To",mobileNumber:"Mobile No.",applicantAddress:"Applicant Address",sentToSectionDate:"Sent to Section Date",assignedOfficer:"Assigned Officer"
};
const TARGET_LABELS={
  "cpgrams-grievances":"CPGRAMS - Grievances",
  "cpgrams-appeals":"CPGRAMS - Appeals",
  "cpgrams-other":"Other Grievance Types",
  "cpgrams-questions":"LAQ / LCQ",
  "rti-applications":"RTI Applications",
  "disha-meetings":"DISHA Meetings",
  "disha-pending-files":"DISHA Pending Files"
};
const DEFAULTS=[
 {target:"cpgrams-grievances",name:"CPGRAMS Grievances Register",fields:CATALOG["cpgrams-grievances"],sortField:"dateReceived",sortDirection:"desc"},
 {target:"cpgrams-appeals",name:"CPGRAMS Appeals Register",fields:CATALOG["cpgrams-appeals"],sortField:"appealReceivedDate",sortDirection:"desc"},
 {target:"cpgrams-other",name:"Other Grievance Types Register",fields:CATALOG["cpgrams-other"],sortField:"dateReceived",sortDirection:"desc"},
 {target:"cpgrams-questions",name:"LAQ / LCQ Register",fields:CATALOG["cpgrams-questions"],sortField:"questionReceivedDate",sortDirection:"desc"},
 {target:"rti-applications",name:"RTI Applications Register",fields:CATALOG["rti-applications"],sortField:"applicationDate",sortDirection:"desc"},
 {target:"disha-meetings",name:"DISHA Meetings Register",fields:CATALOG["disha-meetings"],sortField:"dateOfMeeting",sortDirection:"desc"},
 {target:"disha-pending-files",name:"DISHA Pending Files Register",fields:CATALOG["disha-pending-files"],sortField:"dateOfMeeting",sortDirection:"desc"}
];
const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let db=null,defs=[],selectedId="",started=false;
function label(key){if(LABELS[key])return LABELS[key];return String(key||"").replace(/([a-z])([A-Z])/g,"$1 $2").replace(/[_-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());}
function setStatus(msg,type="secondary"){const e=$("status");if(!e)return;e.className=`ms-auto small align-self-center text-${type}`;e.textContent=msg||"";}
function targetFields(target){return [...new Set([...(CATALOG[target]||[]),...(EXTRA[target]||[])])];}
function rebuildFields(selected=[]){const target=$("target").value,fields=targetFields(target),sel=new Set(selected);$("fields").innerHTML=fields.map(f=>`<option value="${esc(f)}" ${sel.has(f)?"selected":""}>${esc(label(f))}</option>`).join("");$("sortField").innerHTML='<option value="">None</option>'+fields.map(f=>`<option value="${esc(f)}">${esc(label(f))}</option>`).join("");}
function selectedFields(){return [...$("fields").selectedOptions].map(o=>o.value);}
function data(){const fields=selectedFields();if(!$("registerName").value.trim())throw new Error("Enter a Register Name.");if(!fields.length)throw new Error("Select at least one register column.");return{name:$("registerName").value.trim(),target:$("target").value,fields,sortField:$("sortField").value,sortDirection:$("sortDirection").value||"desc",description:$("description").value.trim(),active:$("active").checked,autoFit:$("autoFit").checked,updatedOn:new Date().toISOString()};}
function clearForm(){selectedId="";$("definitionId").value="";$("registerName").value="";$("target").value="cpgrams-grievances";rebuildFields(CATALOG["cpgrams-grievances"]);$("sortField").value="dateReceived";$("sortDirection").value="desc";$("description").value="";$("active").checked=true;$("autoFit").checked=true;}
function filtered(){const q=$("search").value.trim().toLowerCase();if(!q)return defs;return defs.filter(d=>[d.name,TARGET_LABELS[d.target],...(d.fields||[])].join(" ").toLowerCase().includes(q));}
function render(){const rows=filtered();$("recordCount").textContent=`${rows.length} record${rows.length===1?"":"s"}`;const body=$("definitionsTable").querySelector("tbody");if(!rows.length){body.innerHTML='<tr><td colspan="7" class="text-center text-muted py-4">No register definitions found.</td></tr>';return;}body.innerHTML=rows.map((d,i)=>`<tr class="${d.active!==false?'definition-row-active':''}"><td>${i+1}</td><td class="fw-semibold">${esc(d.name||"")}</td><td>${esc(TARGET_LABELS[d.target]||d.target||"")}</td><td>${esc((d.fields||[]).map(label).join(", "))}</td><td>${d.sortField?`${esc(label(d.sortField))} ${esc(d.sortDirection||"desc")}`:"-"}</td><td><span class="badge ${d.active!==false?'bg-success':'bg-secondary'}">${d.active!==false?'Active':'Inactive'}</span></td><td class="text-nowrap"><button class="btn btn-info btn-sm me-1" data-view="${esc(d.id)}"><i class="bi bi-eye"></i> View</button><button class="btn btn-warning btn-sm me-1" data-edit="${esc(d.id)}"><i class="bi bi-pencil"></i> Edit</button><button class="btn btn-danger btn-sm" data-delete="${esc(d.id)}"><i class="bi bi-trash"></i> Delete</button></td></tr>`).join("");body.querySelectorAll("[data-view],[data-edit]").forEach(b=>b.addEventListener("click",()=>edit(b.dataset.view||b.dataset.edit)));body.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",()=>remove(b.dataset.delete)));}
async function load(){setStatus("Loading register definitions...");const snap=await db.collection(COLLECTION).get();defs=snap.docs.map(d=>({id:d.id,...d.data()})).filter(d=>d.deleted!==true).sort((a,b)=>String(a.target||"").localeCompare(String(b.target||""))||String(a.name||"").localeCompare(String(b.name||"")));render();setStatus("Register definitions ready.","success");}
function edit(id){const d=defs.find(x=>x.id===id);if(!d)return;selectedId=id;$("definitionId").value=id;$("registerName").value=d.name||"";$("target").value=d.target||"cpgrams-grievances";rebuildFields(d.fields||[]);$("sortField").value=d.sortField||"";$("sortDirection").value=d.sortDirection||"desc";$("description").value=d.description||"";$("active").checked=d.active!==false;$("autoFit").checked=d.autoFit!==false;window.scrollTo({top:0,behavior:"smooth"});}
async function deactivateOthers(target,exceptId){if(!target)return;const rows=defs.filter(d=>d.target===target&&d.id!==exceptId&&d.active!==false);for(const d of rows){try{await db.collection(COLLECTION).doc(d.id).update({active:false,updatedOn:new Date().toISOString()});}catch(e){console.warn("Unable to deactivate older register definition",e);}}}
async function save(){try{const payload=data();setStatus("Saving register definition...");const ref=await db.collection(COLLECTION).add({...payload,createdOn:new Date().toISOString()});if(payload.active)await deactivateOthers(payload.target,ref.id);clearForm();await load();setStatus("Register definition saved.","success");}catch(e){setStatus(e.message||String(e),"danger");alert(e.message||e);}}
async function update(){if(!selectedId)return alert("Select a register definition to update.");try{const payload=data();setStatus("Updating register definition...");await db.collection(COLLECTION).doc(selectedId).update(payload);if(payload.active)await deactivateOthers(payload.target,selectedId);clearForm();await load();setStatus("Register definition updated.","success");}catch(e){setStatus(e.message||String(e),"danger");alert(e.message||e);}}
async function remove(id=selectedId){if(!id)return alert("Select a register definition to delete.");if(!confirm("Delete this register definition?"))return;try{await db.collection(COLLECTION).doc(id).update({active:false,deleted:true,deletedOn:new Date().toISOString()});clearForm();await load();setStatus("Register definition deleted.","success");}catch(e){setStatus(e.message||String(e),"danger");alert(e.message||e);}}
async function seedDefaults(force=false){try{if(force&&!confirm("Restore the default register definitions? Existing active definitions for the same targets will be made inactive."))return;setStatus("Preparing default register definitions...");if(!defs.length)await load();for(const seed of DEFAULTS){const existing=defs.find(d=>d.target===seed.target&&d.active!==false);if(existing&&!force)continue;if(existing&&force){await db.collection(COLLECTION).doc(existing.id).update({active:false,updatedOn:new Date().toISOString()});}await db.collection(COLLECTION).add({...seed,description:"Built-in editable register layout",active:true,autoFit:true,createdOn:new Date().toISOString(),updatedOn:new Date().toISOString()});}await load();setStatus("Default register definitions are ready.","success");}catch(e){setStatus(e.message||String(e),"danger");alert(e.message||e);}}
async function start(){if(started)return;try{db=window.FMSCrud?await window.FMSCrud.waitForDb():window.db||window.fmsFirebase?.db;}catch(e){setStatus("The data service is still loading.","warning");return;}if(!db)return;started=true;$("target").addEventListener("change",()=>{rebuildFields(CATALOG[$("target").value]||[]);$("sortField").value=(CATALOG[$("target").value]||[])[1]||"";});$("registerDefForm").addEventListener("submit",e=>{e.preventDefault();save();});$("btnUpdate").onclick=update;$("btnDelete").onclick=()=>remove();$("btnClear").onclick=clearForm;$("search").oninput=render;$("btnHome").onclick=()=>location.href="../../index.html";$("btnMasters").onclick=()=>location.href="master-management.html";$("btnReportsMaster").onclick=()=>location.href="reports-master.html";$("btnSeedDefaults").onclick=()=>seedDefaults(true);clearForm();await load();await seedDefaults(false);}
document.addEventListener("DOMContentLoaded",()=>{if(window.fmsFirebaseReady&&window.db)start();else{window.addEventListener("fmsFirebaseReady",start,{once:true});setTimeout(()=>{if(window.db||window.fmsFirebase?.db)start();},1500);}});
window.FMSRegisterFieldCatalog=CATALOG;window.FMSRegisterLabels=LABELS;window.FMSRegisterTargetLabels=TARGET_LABELS;
})(window,document);
