const fs=require('fs');
const assert=require('assert');
const masterHtml=fs.readFileSync('pages/admin/reports-master.html','utf8');
const masterJs=fs.readFileSync('js/reports-master.js','utf8');
const reportsJs=fs.readFileSync('js/reports/reports.js','utf8');
const exportJs=fs.readFileSync('js/services/export-service.js','utf8');
assert(masterHtml.includes('Sectioned reports use the filters inside each section'),'Flat filters must be clearly limited to flat reports');
assert(masterJs.includes('data-section-filter-field'),'Each section must provide its own filter fields');
assert(masterJs.includes('data-section-filter-value'),'Each section must provide its own filter value dropdowns');
assert(masterJs.includes('populateSectionFilterValue'),'Section filter values must be populated from actual field values');
assert(masterJs.includes('filters:[0,1,2].map'),'Up to three filters must persist per section');
assert(reportsJs.includes('function sectionFilterSpecs'),'Reports engine must read section filters');
assert(reportsJs.includes('passesFilters(r,sec.filters)') || reportsJs.includes('passesFilters(x.row,sec.filters)'),'Section filters must be applied per section');
assert(reportsJs.includes('sec.rows=matches.map'),'Each report section must own its filtered row set');
assert(exportJs.includes('rows:sectionRows'),'Export sections must preserve section-specific rows');
assert(exportJs.includes('sec.rows.forEach'),'Excel export must use section-specific rows');
assert(exportJs.includes('drawTable(sec.columns,sec.heading,sec.rows)'),'PDF export must use section-specific rows');
assert(exportJs.includes('tableHtml(sec.columns,sec.heading,sec.rows)'),'Print export must use section-specific rows');
console.log('PASS v1.10.21 Reports Master: section-wise filters with section-specific preview/export rows');
