const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const home=read('index.html');
const form=read('modules/cpgrams/cpgrams.html');
const regHtml=read('modules/cpgrams/cpgrams-register.html');
const regJs=read('modules/cpgrams/cpgrams-register.js');
const cpJs=read('modules/cpgrams/cpgrams.js');
const mode=read('js/filtered-register-mode.js');
const app=read('js/app.js');
function a(c,m){if(!c)throw new Error(m)}
a(home.includes('sidebarCpgramsGrievanceOpenCount'),'Home sidebar must show open CPGRAMS grievance count');
a(home.includes('sidebarCpgramsAppealOpenCount'),'Home sidebar must show open CPGRAMS appeal count');
a(home.includes('filter=pending&fullscreen=1&register=grievances'),'Grievances count must open filtered grievances register');
a(home.includes('filter=appeals-pending&fullscreen=1&register=appeals'),'Appeals count must open filtered appeals register');
a(regHtml.includes('id="appealsRegisterCard"'),'Separate Appeals Register card must exist');
for(const h of ['Sl.No.','Appeal No.','Date Received','Appellant Name','Corresponding Grievance No.','Appeal Status','Action']) a(regHtml.includes(`<th>${h}</th>`),`Appeals Register missing ${h}`);
a(regJs.includes('["registrationNo","Grievance No."]'),'CPGRAMS Grievances Register must include Grievance No.');
a(regJs.includes('["complainantName","Complainant Name"]'),'CPGRAMS Grievances Register must include Complainant Name');
a(regJs.includes('["atrStatusView","ATR Status"]'),'CPGRAMS Grievances Register must include ATR Status');
a(regJs.includes('["finalStatusView","Grievance Status"]'),'CPGRAMS Grievances Register must include Grievance Status');
a(regJs.includes('["appealStatusView","Appeal Status"]'),'CPGRAMS Grievances Register must include Appeal Status');
a(regJs.includes('data-open-doc="${kind}"'),'Register numbers must render as document links');
a(regJs.includes('fileRole||""'),'Document lookup must use attachment role');
a(form.includes('id="appellantName"'),'Appeal form must store Appellant Name');
a(form.includes('id="appealDocument"'),'Appeal form must allow Appeal Document upload');
a(cpJs.includes('{ id: "appealDocument", role: "Appeal Document" }'),'Appeal document must upload with Appeal Document role');
a(mode.includes('registerView==="appeals"'),'Filtered register mode must support Appeals-only view');
a(app.includes('VERSION: "1.9.9"'),'App version must be 1.9.9');
console.log('v1.9.9 CPGRAMS separate Grievances/Appeals register checks passed');
