const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const home=read('index.html');
const cpHtml=read('modules/cpgrams/cpgrams.html');
const dishaHtml=read('modules/disha/disha.html');
const rtiHtml=read('modules/rti/rti.html');
const gw=read('js/grievance-workspace.js');
const dash=read('js/module-inline-dashboard.js');
const disha=read('modules/disha/disha.js');
const app=read('js/app.js');
function a(c,m){if(!c)throw new Error(m)}
a(!home.includes('id="homeFY"'),'Home FY dropdown must be removed');
for(const label of ['CPGRAMS','Prajavani','Public Grievances','Direct Complaints','LAQ','LCQ','Court Cases','VIP References','CMO References','PMO References','Audit Paras','Vigilance Cases','RTI','DISHA']) a(home.includes(`<span>${label}</span>`),`Sidebar missing ${label}`);
a(home.includes('home-sidebar'),'Home sidebar missing');
a(!home.includes('<div class="small lh-sm">Total</div>'),'Home cards must not show Total sub-label');
a(!home.includes('id="homeFY"'),'Home cards must not depend on FY selector');
a(cpHtml.includes('<select id="grievanceFinancialYear"></select>') && cpHtml.includes('<select id="grievanceType">'),'Hidden grievance state controls should remain for compatibility');
a(!cpHtml.includes('for="grievanceFinancialYear"') && !cpHtml.includes('for="grievanceType"'),'Visible Grievances dropdown labels must be removed');
a(cpHtml.includes('<div class="d-none" id="moduleDashboardStatus"></div>'),'Grievances status title must be hidden');
a(rtiHtml.includes('<div class="d-none" id="moduleDashboardStatus"></div>'),'RTI status title must be hidden');
a(dishaHtml.includes('<div class="d-none" id="moduleDashboardStatus"></div>'),'DISHA status title must be hidden');
a(!dishaHtml.includes('for="dishaWorkspaceFY"'),'DISHA FY dropdown label must be removed');
a(gw.includes('function currentFY(){return P()?.currentFY?.() || window.FMSFY?.getCurrentFY?.() || "";}'),'Grievances must force current FY');
a(dash.includes('function selectedFY(){return currentFY();}'),'RTI/DISHA dashboards must force current FY');
a(!dash.includes('All years:'),'All-years workflow title must be removed');
a(!dash.includes('Total: ${metricLink(heldRows.length'),'DISHA meeting card must not mix all-years total');
a(disha.includes('function selectedDishaWorkspaceFY() { return currentDishaFY(); }'),'DISHA home workspace must force current FY');
a(app.includes('VERSION: "1.9.6"'),'App version must be 1.9.6');
console.log('v1.9.6 home sidebar/current-FY dashboard checks passed');
