const fs=require('fs');
const assert=require('assert');
const masterHtml=fs.readFileSync('pages/admin/reports-master.html','utf8');
const masterJs=fs.readFileSync('js/reports-master.js','utf8');
const reportsHtml=fs.readFileSync('pages/reports.html','utf8');
const reportsJs=fs.readFileSync('js/reports/reports.js','utf8');
const exportJs=fs.readFileSync('js/services/export-service.js','utf8');
assert(masterHtml.includes('id="mainHeading"'),'Reports Master must provide custom main heading');
assert(masterHtml.includes('id="btnAddSection"'),'Reports Master must provide Add Section');
assert(masterHtml.includes('id="sectionsContainer"'),'Reports Master must provide section container');
assert(masterJs.includes('function readSections'),'Reports Master must persist section config');
assert(masterJs.includes('mainHeading:$("mainHeading").value.trim()'),'Main heading must be persisted');
assert(masterJs.includes('sections,summaryCards'),'Sections must be persisted with report definition');
assert(reportsHtml.includes('id="reportSectionsContainer"'),'Reports page must have section renderer');
assert(reportsHtml.includes('id="exportPreviewSections"'),'Export preview must have section renderer');
assert(reportsJs.includes('function definitionSections'),'Reports engine must load saved sections');
assert(reportsJs.includes('activeDefinition.mainHeading'),'Custom main heading must drive report title');
assert(reportsJs.includes('sections:reportSections'),'Sections must be passed to export service');
assert(exportJs.includes('function normalizeSections'),'Export service must understand section definitions');
assert(exportJs.includes('sections.forEach(sec=>drawTable'),'PDF export must render sections');
assert(exportJs.includes('sections.map(sec=>tableHtml'),'Print export must render sections');
console.log('PASS v1.10.20 Reports Master: custom main heading + configurable section headings/fields + sectioned exports');
