"use strict";
/* Central reports + custom report definitions - v1.2.2 */
(function(window,document){
const CFG={
  cpgrams:{collection:"cpgrams",dateFields:["dateReceived","dateArised","receivedDate"],dueFields:["dueDate"],name:"GRIEVANCES"},
  rti:{collection:"rtiApplications",dateFields:["applicationDate","dateReceived"],dueFields:["dueDate"],name:"RTI"},
  disha:{collection:"dishaMeetings",dateFields:["dateOfMeeting"],dueFields:["pomDueDate"],name:"DISHA"}
};
const GOV_HEADER=["GOVERNMENT OF TELANGANA","OFFICE OF THE COMMISSIONER, RURAL DEVELOPMENT","#6-3-607, Anand Nagar Colony, Khairatabad,Hyderabad-500 004"];
const LABELS={grievanceType:"Grievance Type",grievanceNumber:"Grievance No.",dateReceived:"Date Received",applicationNumber:"Application No.",applicationDate:"Application Date",dateOfMeeting:"Meeting Date",pomDueDate:"PoM Due Date",pomUploaded:"PoM Uploaded",statusOfMeeting:"Meeting Status",statusOfBills:"Bill Status",meetingExpenditure:"Meeting Expenditure",complainantName:"Complainant Name",applicantName:"Applicant Name",informationSought:"Information Sought",assignedTo:"Assigned To",assignedOfficer:"Assigned Officer",officeCommunicationType:"Communication Type",presentStatus:"Present Status",currentStatus:"Current Status",finalStatus:"Final Status",officeStatus:"Office Status",fileLocation:"File Location",priorityClassification:"Priority Classification",natureOfGrievance:"Grievance Nature"};
let loaded={cpgrams:[],rti:[],disha:[]},definitions=[],reportRows=[],reportColumns=[],reportSummary=[],activeDefinition=null,started=false,exportPreviewType="pdf",activeModule="all";
const $=id=>document.getElementById(id);const label=k=>LABELS[k]||String(k).replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase());
function parseDate(v){if(!v)return null;if(v&&typeof v.toDate==="function")v=v.toDate();if(v&&v.seconds!=null)v=new Date(Number(v.seconds)*1000);const s=String(v);let m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);const d=v instanceof Date?v:new Date(v);return Number.isNaN(d.getTime())?null:d;}
function fmt(v){const d=parseDate(v);return d?d.toLocaleDateString("en-GB"):String(v??"");}
function iso(v){const d=parseDate(v);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`:"";}
function first(r,keys){for(const k of keys||[]){if(r[k]!==undefined&&r[k]!==null&&String(r[k]).trim()!=="")return r[k];}return "";}
function statusOf(r,m){if(m==="cpgrams")return first(r,["officeStatus","currentStatus","finalStatus","status"])||"Pending";if(m==="rti")return first(r,["officeStatus","presentStatus","status","finalStatus"])||"Pending";return first(r,["officeStatus","statusOfMeeting","pomUploaded","status"])||"Pending";}
function subjectOf(r,m){if(m==="cpgrams")return first(r,["subject","grievanceDescription","grievanceNumber"]);if(m==="rti")return first(r,["subject","informationSought","applicationNumber"]);return first(r,["remarks","statusOfMeeting","district"]);}
function dateOf(r,m){return first(r,CFG[m].dateFields);}function dueOf(r,m){return first(r,CFG[m].dueFields);}
function standardRow(m,r){const due=dueOf(r,m),status=statusOf(r,m),today=new Date();today.setHours(0,0,0,0);let delay="",pending="";const dd=parseDate(due);if(dd){dd.setHours(0,0,0,0);if(dd<today&&!isClosedStatus(status,m))delay=Math.floor((today-dd)/86400000);}const bd=parseDate(dateOf(r,m));if(bd&&!isClosedStatus(status,m)){bd.setHours(0,0,0,0);if(bd<=today)pending=Math.floor((today-bd)/86400000);}return {Module:(m==="cpgrams"?"GRIEVANCES":m.toUpperCase()),ID:first(r,["grievanceNumber","applicationNumber","fileNo","officeFileNo","id"]),Date:fmt(dateOf(r,m)),DueDate:fmt(due),Subject:subjectOf(r,m),District:first(r,["district","nameOfDistrict"]),Status:status,"Days Pending":pending,"Days Delayed":delay};}
function isClosedStatus(status,m){const s=String(status||"").trim().toLowerCase();if(m==="disha")return s==="held"||/completed|closed/.test(s);return /closed|disposed|reply obtained|despatched|completed|final reply|replied/.test(s);}
function isOverdueRecord(r,m){const due=parseDate(dueOf(r,m));if(!due||isClosedStatus(statusOf(r,m),m))return false;const today=new Date();today.setHours(0,0,0,0);due.setHours(0,0,0,0);return due<today;}
function todayLabel(){return new Date().toLocaleDateString("en-GB");}
function currentFY(){const d=new Date(),y=d.getMonth()>=3?d.getFullYear():d.getFullYear()-1;return `${y}-${String(y+1).slice(-2)}`;}
function fyBounds(fy){const y=parseInt(String(fy).slice(0,4),10);if(!Number.isFinite(y))return null;return {from:`${y}-04-01`,to:`${y+1}-03-31`};}
function populateFY(){const sel=$("financialYear");if(!sel)return;const cur=currentFY(),start=parseInt(cur.slice(0,4),10);let html="";for(let y=start;y>=2014;y--){const fy=`${y}-${String(y+1).slice(-2)}`;html+=`<option value="${fy}">${fy}${fy===cur?" (Current FY)":""}</option>`;}html+='<option value="custom">Custom Date Range</option>';sel.innerHTML=html;sel.value=cur;applyFYDates(cur);}
function applyFYDates(fy){const b=fyBounds(fy);if(!b)return;$("fromDate").value=b.from;$("toDate").value=b.to;}
function selectedPeriod(){const fy=$("financialYear")?.value;if(fy&&fy!=="custom")return `Financial Year: ${fy}`;const f=$("fromDate").value,t=$("toDate").value;return `Period: ${f||"Start"} to ${t||"Today"}`;}
function reportName(module){if(activeDefinition)return `${activeDefinition.name||"Custom Report"} as on ${todayLabel()}`;if(module==="all")return `All Modules Status Report as on ${todayLabel()}`;return `${CFG[module]?.name||String(module).toUpperCase()} Status Report as on ${todayLabel()}`;}
async function loadAll(){if(!window.db)throw new Error("Firestore is not ready.");for(const m of Object.keys(CFG)){const snap=await db.collection(CFG[m].collection).get();loaded[m]=snap.docs.map(d=>({id:d.id,...d.data()}));}try{const snap=await db.collection("reportDefinitions").get();definitions=snap.docs.map(d=>({id:d.id,...d.data()})).filter(d=>d.active!==false).sort((a,b)=>String(a.name||"").localeCompare(String(b.name||"")));}catch(e){console.warn("Report definitions unavailable",e);definitions=[];}populateDefinitions();}
function populateDefinitions(){const sel=$("customReport"),current=sel.value;sel.innerHTML='<option value="">— Standard report —</option>'+definitions.map(d=>`<option value="${d.id}">${escapeHtml(d.name)} (${String(d.module||"").toUpperCase()})</option>`).join("");if(definitions.some(d=>d.id===current))sel.value=current;}
function dateRangePreset(def){if(!def||def.datePreset==="none")return;const now=new Date(),to=new Date(now),from=new Date(now);if(def.datePreset==="currentFY"){const fy=currentFY();$("financialYear").value=fy;applyFYDates(fy);return;}if(def.datePreset==="last7")from.setDate(now.getDate()-6);else if(def.datePreset==="last30")from.setDate(now.getDate()-29);else if(def.datePreset!=="today")return;const f=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;$("financialYear").value="custom";$("fromDate").value=f(from);$("toDate").value=f(to);}
function inRange(r,m){const from=$("fromDate").value,to=$("toDate").value,d=iso(dateOf(r,m));return (!from||!d||d>=from)&&(!to||!d||d<=to);}
function passesDef(r,def){if(!def?.filterField)return true;let v=r?.[def.filterField];if(v&&typeof v.toDate==="function")v=fmt(v);v=String(v??"");const q=String(def.filterValue??"");switch(def.operator){case"equals":return v.toLowerCase()===q.toLowerCase();case"notEquals":return v.toLowerCase()!==q.toLowerCase();case"gt":return Number(v)>Number(q);case"gte":return Number(v)>=Number(q);case"lt":return Number(v)<Number(q);case"lte":return Number(v)<=Number(q);case"isEmpty":return !v.trim();case"notEmpty":return !!v.trim();default:return v.toLowerCase().includes(q.toLowerCase());}}
function customValue(r,k){const v=r?.[k];if(v&&typeof v.toDate==="function")return fmt(v);if(k.toLowerCase().includes("date")||k.toLowerCase().includes("due")){const d=parseDate(v);if(d)return fmt(v);}return v??"";}
function buildSummary(module,raw,transformed){
 const total=(raw||[]).length;
 if(module==="cpgrams"){
   const disposed=raw.filter(r=>isClosedStatus(statusOf(r,"cpgrams"),"cpgrams")).length;
   return [{label:"Total Grievances Received",value:total},{label:"Disposed / Closed",value:disposed},{label:"Pending",value:Math.max(total-disposed,0)},{label:"Overdue",value:raw.filter(r=>isOverdueRecord(r,"cpgrams")).length}];
 }
 if(module==="rti"){
   const disposed=raw.filter(r=>isClosedStatus(statusOf(r,"rti"),"rti")).length;
   return [{label:"Total RTI Applications",value:total},{label:"Disposed / Completed",value:disposed},{label:"Pending",value:Math.max(total-disposed,0)},{label:"Overdue",value:raw.filter(r=>isOverdueRecord(r,"rti")).length}];
 }
 if(module==="disha"){
   const held=raw.filter(r=>String(r.statusOfMeeting||r.status||"").trim().toLowerCase()==="held").length;
   const postponed=raw.filter(r=>String(r.statusOfMeeting||r.status||"").trim().toLowerCase()==="postponed").length;
   const pomOverdue=raw.filter(r=>isOverdueRecord(r,"disha")&&!/yes|uploaded|completed/i.test(String(r.pomUploaded||r.pomStatus||""))).length;
   return [{label:"Total Meetings",value:total},{label:"Meetings Held",value:held},{label:"To Be Held / Pending",value:Math.max(total-held-postponed,0)},{label:"PoM Overdue",value:pomOverdue}];
 }
 const rows=transformed||[];const closed=rows.filter(r=>isClosedStatus(r.Status||r.presentStatus||r.currentStatus||r.statusOfMeeting,"all")).length,overdue=rows.filter(r=>Number(r["Days Delayed"]||0)>0).length;
 return [{label:"Total Records",value:rows.length},{label:"Closed / Completed",value:closed},{label:"Pending / Open",value:Math.max(rows.length-closed,0)},{label:"Overdue",value:overdue}];
}
function generate(){activeDefinition=definitions.find(d=>d.id===$("customReport").value)||null;if(activeDefinition){generateCustom(activeDefinition);return;}const m=$("reportModule").value;activeModule=m;let out=[],raw=[];if(m==="all"){for(const mod of Object.keys(loaded)){const src=loaded[mod].filter(r=>inRange(r,mod));raw.push(...src.map(r=>({...r,__module:mod})));out.push(...src.map(r=>standardRow(mod,r)));}}else{raw=loaded[m].filter(r=>inRange(r,m));out=raw.map(r=>standardRow(m,r));}reportRows=out;reportColumns=["Module","ID","Date","DueDate","Subject","District","Status","Days Pending","Days Delayed"].map(k=>({key:k,label:k}));reportSummary=buildSummary(m,raw,out);render(reportName(m));}
function generateCustom(def){const modules=def.module==="all"?Object.keys(loaded):[def.module];let out=[],raw=[];activeModule=def.module||"all";if(def.module==="all"){for(const m of modules){for(const r of loaded[m].filter(x=>inRange(x,m))){const sr=standardRow(m,r);if(passesDef(sr,def)){out.push(sr);raw.push({...r,__module:m});}}}reportColumns=(def.fields||Object.keys(out[0]||{})).map(k=>({key:k,label:label(k)}));}else{let source=(loaded[def.module]||[]).filter(x=>inRange(x,def.module)).filter(x=>passesDef(x,def));raw=source.slice();if(def.sortField)source.sort((a,b)=>String(customValue(a,def.sortField)??"").localeCompare(String(customValue(b,def.sortField)??""),undefined,{numeric:true})*(def.sortDirection==="desc"?-1:1));for(const r of source){const o={};(def.fields||[]).forEach(k=>o[k]=customValue(r,k));out.push(o);}reportColumns=(def.fields||[]).map(k=>({key:k,label:label(k)}));}if(def.module==="all"&&def.sortField)out.sort((a,b)=>String(a[def.sortField]??"").localeCompare(String(b[def.sortField]??""),undefined,{numeric:true})*(def.sortDirection==="desc"?-1:1));reportRows=out;reportSummary=buildSummary(def.module,raw,out);render(reportName(def.module));}
function render(title){$("reportTitle").textContent=title;$("recordCount").textContent=reportRows.length+" records";const th=$("reportTable").querySelector("thead"),tb=$("reportTable").querySelector("tbody");th.innerHTML='<tr>'+reportColumns.map(c=>`<th>${escapeHtml(c.label)}</th>`).join('')+'</tr>';tb.innerHTML=reportRows.length?reportRows.map(r=>'<tr>'+reportColumns.map(c=>`<td>${escapeHtml(r[c.key]??"")}</td>`).join('')+'</tr>'):`<tr><td colspan="${Math.max(reportColumns.length,1)}" class="text-center p-5 text-muted">No records found.</td></tr>`;const colors=["primary","success","warning","danger"];$("summaryCards").innerHTML=reportSummary.map((x,i)=>`<div class="col-xl-3 col-md-6"><div class="card border-${colors[i%colors.length]} summary-card h-100"><div class="card-body text-center"><div class="text-muted">${escapeHtml(x.label)}</div><h3 class="text-${colors[i%colors.length]}">${escapeHtml(x.value)}</h3></div></div></div>`).join("");$("summaryPeriod").textContent=selectedPeriod();$("reportStatus").textContent=`Generated ${new Date().toLocaleString("en-IN")}`;}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function exportOpts(){const fy=$("financialYear")?.value;return {rows:reportRows,columns:reportColumns,title:$("reportTitle").textContent,filename:$("reportTitle").textContent,headerLines:GOV_HEADER,summary:reportSummary,financialYear:fy&&fy!=="custom"?fy:"",periodLabel:fy==="custom"?selectedPeriod():"",shareText:`${GOV_HEADER.join("\n")}\n\n${$("reportTitle").textContent}\n${selectedPeriod()}\nRecords: ${reportRows.length}`};}
function renderExportPreview(){const title=$("reportTitle").textContent||"FMS Report";$("exportPreviewTitle").textContent="Export Report — Preview";$("exportPreviewMeta").textContent=`${title} • ${reportRows.length} record(s)`;$("exportPreviewGov1").textContent=GOV_HEADER[0];$("exportPreviewGov2").textContent=GOV_HEADER[1];$("exportPreviewGov3").textContent=GOV_HEADER[2];$("exportPreviewReportTitle").textContent=title;$("exportPreviewReportMeta").textContent=selectedPeriod()+` • Records: ${reportRows.length}`;$("exportPreviewSummary").innerHTML='<div class="fw-bold text-center mb-2">SUMMARY</div><div class="row g-2">'+reportSummary.map(x=>`<div class="col-md-3 col-6"><div class="border rounded p-2 text-center h-100"><div class="small text-muted">${escapeHtml(x.label)}</div><div class="fs-5 fw-bold">${escapeHtml(x.value)}</div></div></div>`).join("")+"</div>";const th=$("exportPreviewTable").querySelector("thead"),tb=$("exportPreviewTable").querySelector("tbody");th.innerHTML='<tr>'+reportColumns.map(c=>`<th>${escapeHtml(c.label||c.key)}</th>`).join('')+'</tr>';tb.innerHTML=reportRows.map(r=>'<tr>'+reportColumns.map(c=>`<td>${escapeHtml(r[c.key]??"")}</td>`).join('')+'</tr>').join('');$("exportPreviewFormat").value=exportPreviewType==="print"?"pdf":exportPreviewType;$("exportPreviewStatus").textContent="";updateDeviceShareNote();}
function updateDeviceShareNote(){const note=$("deviceShareNote"),btn=$("btnPreviewShare");if(!note||!btn)return;btn.disabled=false;if(navigator.share){note.textContent="Share will open the device/browser share menu. File sharing is used when permitted; otherwise the report is shared as text or downloaded automatically.";note.classList.add("share-ready");}else{note.textContent="Native device sharing is unavailable in this browser. Share will download the selected report file instead.";note.classList.remove("share-ready");}}
function openExportPreview(type){try{if(!Array.isArray(reportRows)||!reportRows.length)throw new Error("No records are available to export.");exportPreviewType=type||"pdf";renderExportPreview();$("exportPreviewBackdrop").classList.add("open");document.body.style.overflow="hidden";if(type==="print")setTimeout(()=>$("btnPreviewPrint")?.focus(),50);else setTimeout(()=>$("btnPreviewShare")?.focus(),50);}catch(e){alert(e.message||e);}}
function closeExportPreview(){$("exportPreviewBackdrop")?.classList.remove("open");document.body.style.overflow="";}
async function previewDownload(){const status=$("exportPreviewStatus");try{const type=$("exportPreviewFormat").value,opts=exportOpts();status.textContent="Preparing file...";if(type==="excel")await FMSExportService.toExcel(opts);if(type==="pdf")await FMSExportService.toPDF(opts);if(type==="jpeg")await FMSExportService.toJPEG(opts);status.textContent="Downloaded successfully.";}catch(e){status.textContent="";alert(e.message||e);}}
async function previewPrint(){const status=$("exportPreviewStatus");try{status.textContent="Opening print preview...";await FMSExportService.printRows(exportOpts());status.textContent="";}catch(e){status.textContent="";alert(e.message||e);}}
async function previewShare(){const status=$("exportPreviewStatus");try{const type=$("exportPreviewFormat").value;status.textContent="Preparing share...";const result=await FMSExportService.shareFile(type,exportOpts());if(result?.cancelled)status.textContent="Share cancelled.";else if(result?.shared)status.textContent=result.fileShared?"Report file shared.":"Report details shared. The file remains available from Download.";else if(result?.downloaded)status.textContent=result.message||"Sharing was not permitted; report downloaded instead.";else status.textContent="";}catch(e){console.error(e);status.textContent="Unable to use device sharing. Please use Download.";}}
async function shareWhatsApp(){const preview=reportRows.slice(0,15).map((r,i)=>`${i+1}. ${reportColumns.slice(0,4).map(c=>`${c.label}: ${r[c.key]??""}`).join(" | ")}`).join("\n");await window.FMSWhatsAppService?.compose({module:"REPORTS",title:$("reportTitle").textContent,summaryText:`${selectedPeriod()}\nRecords: ${reportRows.length}\n${preview}`});}
async function init(){if(started)return;started=true;$("btnHome").onclick=()=>location.href="../index.html";$("btnMasters").onclick=()=>location.href="admin/master-management.html";$("btnReportsMaster").onclick=()=>location.href="admin/reports-master.html";$("btnRefresh").onclick=async()=>{await loadAll();generate();};$("btnGenerate").onclick=generate;$("btnExcel").onclick=()=>openExportPreview("excel");$("btnPDF").onclick=()=>openExportPreview("pdf");$("btnJPEG").onclick=()=>openExportPreview("jpeg");$("btnPrint").onclick=()=>openExportPreview("print");$("btnWhatsApp").onclick=shareWhatsApp;$("btnCloseExportPreview").onclick=closeExportPreview;$("btnPreviewDownload").onclick=previewDownload;$("btnPreviewPrint").onclick=previewPrint;$("btnPreviewShare").onclick=previewShare;$("exportPreviewFormat").onchange=e=>{exportPreviewType=e.target.value;updateDeviceShareNote();};$("exportPreviewBackdrop").addEventListener("click",e=>{if(e.target===$("exportPreviewBackdrop"))closeExportPreview();});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("exportPreviewBackdrop")?.classList.contains("open"))closeExportPreview();});$("customReport").onchange=()=>{activeDefinition=definitions.find(d=>d.id===$("customReport").value)||null;if(activeDefinition){$("reportModule").value=activeDefinition.module==="all"?"all":activeDefinition.module;dateRangePreset(activeDefinition);}};$("financialYear").onchange=e=>{if(e.target.value!=="custom")applyFYDates(e.target.value);generate();};["fromDate","toDate"].forEach(id=>$(id).addEventListener("change",()=>{$("financialYear").value="custom";}));try{await loadAll();populateFY();const q=new URLSearchParams(location.search).get("module");if(q&&CFG[q])$("reportModule").value=q;generate();}catch(e){$("reportStatus").textContent="Unable to load reports: "+(e.message||e);console.error(e);}}
document.addEventListener("DOMContentLoaded",()=>{if(window.fmsFirebaseReady&&window.db)init();else{window.addEventListener("fmsFirebaseReady",init,{once:true});setTimeout(()=>{if(window.db)init();},1600);}});
})(window,document);
