"use strict";
(function(window,document){
const CATALOG={
 cpgrams:["grievanceType","grievanceNumber","dateReceived","dueDate","complainantName","mobileNumber","district","mandal","village","subject","category","source","priority","priorityClassification","natureOfGrievance","assignedOfficer","section","fileLocation","currentStatus","finalStatus","officeStatus","officeCommunicationType","remarks"],
 rti:["applicationNumber","applicationDate","dueDate","applicantName","mobileNumber","district","mandal","village","subject","informationSought","assignedTo","section","presentStatus","officeStatus","officeCommunicationType","remarks"],
 disha:["district","dateOfMeeting","pomDueDate","pomUploaded","statusOfMeeting","statusOfBills","meetingExpenditure","officeStatus","officeCommunicationType","remarks"],
 all:["Module","ID","Date","DueDate","Subject","District","Status","Days Pending","Days Delayed"]
};
const LABELS={grievanceType:"Grievance Type",grievanceNumber:"Grievance No.",dateReceived:"Date Received",applicationNumber:"Application No.",applicationDate:"Application Date",dateOfMeeting:"Meeting Date",pomDueDate:"PoM Due Date",pomUploaded:"PoM Uploaded",statusOfMeeting:"Meeting Status",statusOfBills:"Bill Status",meetingExpenditure:"Meeting Expenditure",complainantName:"Complainant Name",applicantName:"Applicant Name",informationSought:"Information Sought",assignedTo:"Assigned To",assignedOfficer:"Assigned Officer",officeCommunicationType:"Communication Type",presentStatus:"Present Status",currentStatus:"Current Status",finalStatus:"Final Status",officeStatus:"Office Status",fileLocation:"File Location",priorityClassification:"Priority Classification",natureOfGrievance:"Grievance Nature"};
let db=null,defs=[],selectedId=null,started=false;const $=id=>document.getElementById(id);const moduleLabel=m=>m==="cpgrams"?"GRIEVANCES":String(m||"").toUpperCase();const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const label=k=>LABELS[k]||k.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase());
function setStatus(m,c="muted"){$("status").className=`ms-auto small align-self-center text-${c}`;$("status").textContent=m;}
function rebuildFields(){const module=$("module").value,arr=CATALOG[module]||[];const old=[...$("fields").selectedOptions].map(o=>o.value);$("fields").innerHTML=arr.map(k=>`<option value="${k}" ${old.includes(k)?"selected":""}>${esc(label(k))}</option>`).join("");const opts='<option value="">None</option>'+arr.map(k=>`<option value="${k}">${esc(label(k))}</option>`).join("");const ff=$("filterField").value,sf=$("sortField").value;$("filterField").innerHTML=opts;$("sortField").innerHTML=opts;if(arr.includes(ff))$("filterField").value=ff;if(arr.includes(sf))$("sortField").value=sf;}
function clear(){selectedId=null;$("reportDefForm").reset();$("active").checked=true;$("module").value="cpgrams";rebuildFields();$("definitionId").value="";}
function data(){const fields=[...$("fields").selectedOptions].map(o=>o.value);if(!$("reportName").value.trim())throw new Error("Report Name is required.");if(!fields.length)throw new Error("Select at least one report field.");return {name:$("reportName").value.trim(),module:$("module").value,fields,filterField:$("filterField").value,operator:$("operator").value,filterValue:$("filterValue").value.trim(),sortField:$("sortField").value,sortDirection:$("sortDirection").value,datePreset:$("datePreset").value,description:$("description").value.trim(),active:$("active").checked,modifiedOn:firebase.firestore.FieldValue.serverTimestamp()};}
async function load(){setStatus("Loading report definitions...");const snap=await db.collection("reportDefinitions").get();defs=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.name||"").localeCompare(String(b.name||"")));render();setStatus(`${defs.length} report definitions loaded`,"success");}
function filtered(){const q=$("search").value.trim().toLowerCase();return !q?defs:defs.filter(d=>JSON.stringify(d).toLowerCase().includes(q));}
function render(){const arr=filtered();$("recordCount").textContent=`${arr.length} records`;$("definitionsTable").querySelector("tbody").innerHTML=arr.length?arr.map((d,i)=>`<tr><td>${i+1}</td><td>${esc(d.name)}</td><td>${esc(moduleLabel(d.module))}</td><td>${esc((d.fields||[]).map(label).join(", "))}</td><td>${d.filterField?esc(`${label(d.filterField)} ${d.operator||""} ${d.filterValue||""}`):""}</td><td>${d.active===false?'<span class="badge bg-secondary">Inactive</span>':'<span class="badge bg-success">Active</span>'}</td><td class="text-nowrap"><button class="btn btn-sm btn-primary" data-edit="${d.id}">Edit</button> <button class="btn btn-sm btn-outline-danger" data-del="${d.id}">Delete</button></td></tr>`).join(""):'<tr><td colspan="7" class="text-center text-muted p-4">No custom report definitions.</td></tr>';document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>remove(b.dataset.del));}
function edit(id){const d=defs.find(x=>x.id===id);if(!d)return;selectedId=id;$("definitionId").value=id;$("reportName").value=d.name||"";$("module").value=d.module||"cpgrams";rebuildFields();[...$("fields").options].forEach(o=>o.selected=(d.fields||[]).includes(o.value));$("filterField").value=d.filterField||"";$("operator").value=d.operator||"contains";$("filterValue").value=d.filterValue||"";$("sortField").value=d.sortField||"";$("sortDirection").value=d.sortDirection||"asc";$("datePreset").value=d.datePreset||"none";$("description").value=d.description||"";$("active").checked=d.active!==false;window.scrollTo({top:0,behavior:"smooth"});}
async function save(){try{const d=data();d.createdOn=firebase.firestore.FieldValue.serverTimestamp();await db.collection("reportDefinitions").add(d);clear();await load();setStatus("Custom report saved.","success");}catch(e){alert(e.message||e);}}
async function update(){if(!selectedId)return alert("Select a report definition to update.");try{await db.collection("reportDefinitions").doc(selectedId).update(data());clear();await load();setStatus("Custom report updated.","success");}catch(e){alert(e.message||e);}}
async function remove(id=selectedId){if(!id)return alert("Select a report definition to delete.");if(!confirm("Delete this custom report definition?"))return;await db.collection("reportDefinitions").doc(id).delete();clear();await load();}
async function seedDefaults(){if(defs.length)return;const seeds=[{name:"GRIEVANCES Status Register",module:"cpgrams",fields:["grievanceType","grievanceNumber","dateReceived","dueDate","complainantName","district","subject","category","currentStatus"],datePreset:"currentFY"},{name:"RTI Pendency Register",module:"rti",fields:["applicationNumber","applicationDate","dueDate","applicantName","district","informationSought","presentStatus"],datePreset:"currentFY"},{name:"DISHA Meeting Status Register",module:"disha",fields:["district","dateOfMeeting","pomDueDate","pomUploaded","statusOfMeeting","statusOfBills","meetingExpenditure"],datePreset:"currentFY"}];for(const s of seeds){try{await db.collection("reportDefinitions").add({...s,operator:"contains",filterField:"",filterValue:"",sortField:"",sortDirection:"asc",description:"Built-in editable custom report",active:true,createdOn:firebase.firestore.FieldValue.serverTimestamp()});}catch(e){console.warn("Unable to seed report definition",e);}}await load();}
async function exportDefs(type){try{const rows=filtered().map((d,i)=>({sl:i+1,name:d.name,module:String(d.module||"").toUpperCase(),fields:(d.fields||[]).map(label).join(", "),filter:d.filterField?`${label(d.filterField)} ${d.operator||""} ${d.filterValue||""}`:"",sort:d.sortField?`${label(d.sortField)} ${d.sortDirection||""}`:"",active:d.active===false?"Inactive":"Active"}));const cols=[{key:"sl",label:"Sl.No"},{key:"name",label:"Report Name"},{key:"module",label:"Module"},{key:"fields",label:"Columns"},{key:"filter",label:"Filter"},{key:"sort",label:"Sort"},{key:"active",label:"Status"}],title="FMS Reports Master Register";if(type==="excel")await FMSExportService.toExcel({rows,columns:cols,title});if(type==="pdf")await FMSExportService.toPDF({rows,columns:cols,title});if(type==="jpeg")await FMSExportService.toJPEG({rows,columns:cols,title});if(type==="print")await FMSExportService.printRows({rows,columns:cols,title});}catch(e){alert(e.message||e);}}
async function start(){if(started)return;db=window.db||window.fmsFirebase?.db;if(!db)return;started=true;$("module").onchange=rebuildFields;rebuildFields();$("reportDefForm").onsubmit=e=>{e.preventDefault();save();};$("btnUpdate").onclick=update;$("btnDelete").onclick=()=>remove();$("btnClear").onclick=clear;$("search").oninput=render;$("btnHome").onclick=()=>location.href="../../index.html";$("btnMasters").onclick=()=>location.href="master-management.html";$("btnReports").onclick=()=>location.href="../reports.html";await load();await seedDefaults();}
document.addEventListener("DOMContentLoaded",()=>{if(window.fmsFirebaseReady&&window.db)start();else{window.addEventListener("fmsFirebaseReady",start,{once:true});setTimeout(()=>{if(window.db)start();},1500);}});
window.FMSReportFieldCatalog=CATALOG;window.FMSReportLabels=LABELS;
})(window,document);
