let documentRows=[];let selectedDocumentId=null;let documentDashboardFilter="";const desc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function initializeDocuments(){await RGMS.store.loadCollection(STORAGE_KEYS.DOCUMENTS);documentRows=getAllRecords(STORAGE_KEYS.DOCUMENTS);const isAdmin=window.RGMS?.roleAccess?.isConfigured?.()?window.RGMS.roleAccess.can('documents','add'):RGMS.auth.getSession()?.role==='Admin';const form=document.getElementById('docAdminForm');if(form)form.hidden=!isAdmin;bindDocumentEvents();renderDocuments();clearDocumentForm();}
function bindDocumentEvents(){document.getElementById('docUpload')?.addEventListener('click',uploadDocument);document.getElementById('docUpdate')?.addEventListener('click',updateSelectedDocument);document.getElementById('docDelete')?.addEventListener('click',deleteDocument);document.getElementById('docClear')?.addEventListener('click',clearDocumentForm);document.getElementById('docRefresh')?.addEventListener('click',refreshDocuments);document.getElementById('docSearch')?.addEventListener('input',renderDocuments);document.querySelectorAll('[data-document-dashboard]').forEach(c=>{const run=()=>{documentDashboardFilter=c.dataset.documentDashboard||'';renderDocuments();};c.addEventListener('click',run);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run();}});});}
async function uploadDocument(){const title=document.getElementById('docTitle').value.trim();const file=document.getElementById('docFile').files[0];if(!title||!file)return dm('Document title and file are required.',true);if(file.size>20*1024*1024)return dm('Maximum file size is 20 MB.',true);try{dm('Uploading...');const {ref,uploadBytes,getDownloadURL}=await import('https://www.gstatic.com/firebasejs/12.16.0/firebase-storage.js');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`documents/${Date.now()}_${safe}`;const storageRef=ref(RGMS.firebase.storage,path);await uploadBytes(storageRef,file,{contentType:file.type||undefined});const url=await getDownloadURL(storageRef);const rec={title,category:document.getElementById('docCategory').value,documentDate:document.getElementById('docDate').value||new Date().toISOString().slice(0,10),description:document.getElementById('docDescription').value.trim(),fileName:file.name,fileType:file.type||'',fileSize:file.size,storagePath:path,downloadUrl:url,uploadedBy:RGMS.auth.getSession()?.email||'',uploadedOn:new Date().toISOString()};await insertRecord(STORAGE_KEYS.DOCUMENTS,rec);await refreshDocuments();dm('Document uploaded successfully.');clearDocumentForm();}catch(e){console.error(e);dm(e.message||'Upload failed.',true);}}
async function deleteDocument(){if(!selectedDocumentId)return dm('Select a document first.',true);if(!confirm('Delete this document record and stored file?'))return;const r=documentRows.find(x=>String(x.id)===String(selectedDocumentId));try{if(r?.storagePath){const {ref,deleteObject}=await import('https://www.gstatic.com/firebasejs/12.16.0/firebase-storage.js');await deleteObject(ref(RGMS.firebase.storage,r.storagePath)).catch(()=>{});}await RGMS.store.deleteRecord(STORAGE_KEYS.DOCUMENTS,selectedDocumentId);await refreshDocuments();dm('Document deleted.');clearDocumentForm();}catch(e){console.error(e);dm(e.message||'Delete failed.',true);}}
async function refreshDocuments(){await RGMS.store.refreshCollection(STORAGE_KEYS.DOCUMENTS,{retries:3});documentRows=getAllRecords(STORAGE_KEYS.DOCUMENTS);renderDocuments();}
function renderDocuments(){const q=(document.getElementById('docSearch')?.value||'').toLowerCase();const ym=new Date().toISOString().slice(0,7);const rows=documentRows.filter(r=>(!documentDashboardFilter||documentDashboardFilter==='total'||(documentDashboardFilter==='month'&&String(r.uploadedOn||r.documentDate||'').slice(0,7)===ym))&&[r.title,r.category,r.description,r.fileName].some(v=>String(v||'').toLowerCase().includes(q))).sort((a,b)=>String(b.uploadedOn).localeCompare(String(a.uploadedOn)));document.getElementById('documentsBody').innerHTML=rows.map(r=>`<tr><td>${desc(formatDate(r.documentDate))}</td><td><strong>${desc(r.title)}</strong><div class="small">${desc(r.description)}</div></td><td>${desc(r.category)}</td><td>${r.downloadUrl?`<a class="file-link" href="${desc(r.downloadUrl)}" target="_self">${desc(r.fileName||'Open file')}</a>`:''}</td><td>${desc(r.uploadedBy)}</td><td><div class="rg-grid-actions">${r.downloadUrl?`<a class="rg-icon-btn rg-view" title="View document" aria-label="View document" href="${desc(r.downloadUrl)}" target="_self" rel="noopener noreferrer">👁️</a>`:''}<button class="rg-icon-btn rg-update" title="Modify document details" aria-label="Modify document details" onclick="selectDocument('${desc(r.id)}')">✏️</button><button class="rg-icon-btn rg-delete" title="Delete document" aria-label="Delete document" onclick="deleteDocumentById('${desc(r.id)}')">🗑️</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No documents uploaded.</td></tr>';document.getElementById('docTotal').textContent=documentRows.length;document.getElementById('docMonth').textContent=documentRows.filter(r=>String(r.uploadedOn||r.documentDate||'').slice(0,7)===ym).length;const f=document.getElementById('documentActiveFilter');if(f){f.textContent=documentDashboardFilter?`Filter: ${documentDashboardFilter==='month'?'Uploaded this month only':'All documents'} — ${rows.length} record(s). Click Total Documents to clear.`:'';f.style.display=documentDashboardFilter?'block':'none';}}
async function deleteDocumentById(id){const r=documentRows.find(x=>String(x.id)===String(id));if(!r)return;if(!confirm(`Delete document ${r.title||""}?`))return;try{if(r.storagePath){const {ref,deleteObject}=await import('https://www.gstatic.com/firebasejs/12.16.0/firebase-storage.js');await deleteObject(ref(RGMS.firebase.storage,r.storagePath)).catch(()=>{});}await RGMS.store.deleteRecord(STORAGE_KEYS.DOCUMENTS,id);await refreshDocuments();dm("Document deleted.");}catch(e){console.error(e);dm(e.message||"Delete failed.",true);}}
window.deleteDocumentById=deleteDocumentById;
function selectDocument(id){selectedDocumentId=id;const r=documentRows.find(x=>String(x.id)===String(id));if(!r)return;document.getElementById('docTitle').value=r.title||'';document.getElementById('docCategory').value=r.category||'Association';document.getElementById('docDate').value=r.documentDate||'';document.getElementById('docDescription').value=r.description||'';dm('Document selected. Modify the details and click Modify Selected.');}
async function updateSelectedDocument(){
  if(!selectedDocumentId)return dm('Select a document first.',true);
  if(window.RGMS?.roleAccess?.isConfigured?.()&&!window.RGMS.roleAccess.can('documents',selectedDocumentId?'update':'add'))return dm('This role does not have permission to modify documents.',true);if(!window.RGMS?.roleAccess?.isConfigured?.()&&RGMS.auth.getSession()?.role!=='Admin')return dm('Only Admin can modify documents.',true);
  const r=documentRows.find(x=>String(x.id)===String(selectedDocumentId));
  if(!r)return;
  const title=document.getElementById('docTitle').value.trim();
  if(!title)return dm('Document Title is required.',true);
  const updated={
    ...r,
    title,
    category:document.getElementById('docCategory').value,
    documentDate:document.getElementById('docDate').value,
    description:document.getElementById('docDescription').value.trim(),
    updatedOn:new Date().toISOString(),
    updatedBy:RGMS.auth.getSession()?.email||''
  };
  try{
    await RGMS.store.setRecord(STORAGE_KEYS.DOCUMENTS,r.id,updated);
    await refreshDocuments();
    dm('Document details modified.');
  }catch(e){console.error(e);dm(e.message||'Modify failed.',true);}
}
window.updateSelectedDocument=updateSelectedDocument;

function clearDocumentForm(){selectedDocumentId=null;['docTitle','docDate','docDescription'].forEach(id=>document.getElementById(id).value='');document.getElementById('docCategory').value='Association';document.getElementById('docFile').value='';}
function dm(t,e=false){const x=document.getElementById('docMessage');x.textContent=t;x.className='message '+(e?'error':'ok');}window.initializeDocuments=initializeDocuments;window.selectDocument=selectDocument;