let meetingRows=[];let selectedMeetingId=null;const mesc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function initializeMeetings(){
await RGMS.store.loadCollection(STORAGE_KEYS.MEETINGS);meetingRows=getAllRecords(STORAGE_KEYS.MEETINGS);bindMeetingEvents();renderMeetings();clearMeetingForm();}
function bindMeetingEvents(){const m={meetingSave:saveMeeting,meetingUpdate:updateMeeting,meetingDelete:deleteMeeting,meetingClear:clearMeetingForm,meetingRefresh:refreshMeetings,meetingPrint:printMeeting};Object.entries(m).forEach(([id,fn])=>document.getElementById(id)?.addEventListener('click',fn));document.getElementById('meetingSearch')?.addEventListener('input',renderMeetings);}
function mf(){return {meetingNo:document.getElementById('meetingNo').value,meetingDate:document.getElementById('meetingDate').value,meetingTime:document.getElementById('meetingTime').value,meetingType:document.getElementById('meetingType').value,status:document.getElementById('meetingStatus').value,venue:document.getElementById('meetingVenue').value.trim(),chairperson:document.getElementById('meetingChair').value.trim(),secretary:document.getElementById('meetingSecretary').value.trim(),quorum:document.getElementById('meetingQuorum').value,agenda:document.getElementById('meetingAgenda').value.trim(),attendance:document.getElementById('meetingAttendance').value.trim(),minutes:document.getElementById('meetingMinutes').value.trim(),actionItems:document.getElementById('meetingActions').value.trim(),nextMeetingDate:document.getElementById('meetingNextDate').value,meetingLink:document.getElementById('meetingLink').value.trim()};}
function nextMeetingNo(){return `MTG-${new Date().getFullYear()}-${String(meetingRows.length+1).padStart(4,'0')}`;}
async function uploadMeetingFile(file,meetingNo){if(!file)return null;const {ref,uploadBytes,getDownloadURL}=await import('https://www.gstatic.com/firebasejs/12.16.0/firebase-storage.js');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const r=ref(RGMS.firebase.storage,`meeting-attachments/${meetingNo}/${Date.now()}_${safe}`);await uploadBytes(r,file);return {name:file.name,url:await getDownloadURL(r),path:r.fullPath};}
async function publishMeetingToNoticeBoard(r){
  try {
    await RGMS.store.refreshCollection(STORAGE_KEYS.NOTICES,{retries:2});
    const notices=getAllRecords(STORAGE_KEYS.NOTICES);
    const existing=notices.find(n=>String(n.meetingId||'')===String(r.id||'') || String(n.meetingNo||'')===String(r.meetingNo||''));
    const s=RGMS.auth.getSession()||{};
    const when=[r.meetingDate,r.meetingTime].filter(Boolean).join(' ');
    const message=[
      `Meeting No.: ${r.meetingNo||''}`,
      `Date & Time: ${when}`,
      `Type: ${r.meetingType||''}`,
      `Venue: ${r.venue||''}`,
      r.agenda?`Agenda: ${r.agenda}`:''
    ].filter(Boolean).join('\n');
    const payload={
      ...(existing||{}),
      id:existing?.id || `MEETING-NOTICE-${r.id||r.meetingNo}`,
      meetingId:r.id||'', meetingNo:r.meetingNo||'',
      title:`Meeting Scheduled - ${r.meetingNo||'Meeting'}`,
      message,type:'Meeting',status:'Published',audience:'All Residents',
      date:r.meetingDate||new Date().toISOString().slice(0,10),
      createdOn:existing?.createdOn||new Date().toISOString(),
      updatedOn:new Date().toISOString(),createdBy:s.role||'',
      publishedByName:s.ownerName||s.name||s.displayName||s.role||'Office Bearer'
    };
    if(existing) await RGMS.store.setRecord(STORAGE_KEYS.NOTICES,existing.id,payload);
    else await RGMS.store.insertRecord(STORAGE_KEYS.NOTICES,payload);
  } catch(e) {
    console.warn('Meeting Notice Board publication failed:',e);
    throw new Error(`Meeting saved, but Notice Board publication failed: ${e.message||e}`);
  }
}
async function saveMeeting(){if(selectedMeetingId){await updateMeeting();return;}const r=mf();if(!r.meetingDate)return mm('Meeting Date is required.',true);r.meetingNo=r.meetingNo||nextMeetingNo();const file=await uploadMeetingFile(document.getElementById('meetingFile').files[0],r.meetingNo);if(file)r.attachment=file;r.createdOn=new Date().toISOString();r.createdBy=RGMS.auth.getSession()?.email||'';await insertRecord(STORAGE_KEYS.MEETINGS,r);await refreshMeetings();try{await RGMS.store.refreshCollection(STORAGE_KEYS.MEETINGS,{retries:2});const saved=getAllRecords(STORAGE_KEYS.MEETINGS).find(x=>String(x.meetingNo)===String(r.meetingNo));await publishMeetingToNoticeBoard(saved||r);mm(`Meeting ${r.meetingNo} saved and published to Notice Board.`);}catch(e){mm(e.message||`Meeting ${r.meetingNo} saved, but Notice Board publication failed.`,true);}clearMeetingForm();}
async function updateMeeting(){if(!selectedMeetingId)return mm('Select a meeting first.',true);const r=mf();if(!r.meetingDate)return mm('Meeting Date is required.',true);const file=await uploadMeetingFile(document.getElementById('meetingFile').files[0],r.meetingNo);if(file)r.attachment=file;await RGMS.store.setRecord(STORAGE_KEYS.MEETINGS,selectedMeetingId,{...r,updatedOn:new Date().toISOString()});await refreshMeetings();mm('Meeting updated.');clearMeetingForm();}
async function deleteMeeting(){if(!selectedMeetingId)return mm('Select a meeting first.',true);if(!confirm('Delete this meeting record?'))return;await RGMS.store.deleteRecord(STORAGE_KEYS.MEETINGS,selectedMeetingId);await refreshMeetings();mm('Meeting deleted.');clearMeetingForm();}
async function refreshMeetings(){await RGMS.store.refreshCollection(STORAGE_KEYS.MEETINGS,{retries:3});meetingRows=getAllRecords(STORAGE_KEYS.MEETINGS);renderMeetings();}
function renderMeetings(){const rawQ=(document.getElementById('meetingSearch')?.value||''); const q=rawQ.toLowerCase(); const today=new Date().toISOString().slice(0,10); const specialUpcoming=rawQ==='__RG_UPCOMING__'; const specialHeld=rawQ==='__RG_HELD__'; const specialPostponed=rawQ==='__RG_POSTPONED__'; const dash=window.RGMS?.consumeDashboardFilter?.('meetings'); const rows=meetingRows.filter(r=>{ if(specialUpcoming||dash?.filter==='__UPCOMING__') return r.meetingDate>=today&&r.status==='To be held'; if(specialHeld) return r.status==='Held'; if(specialPostponed) return r.status==='Postponed'; return [r.meetingNo,r.meetingType,r.venue,r.chairperson,r.status].some(v=>String(v||'').toLowerCase().includes(q)); }).sort((a,b)=>String(a.meetingDate).localeCompare(String(b.meetingDate)));document.getElementById('meetingsBody').innerHTML=rows.map(r=>`<tr><td>${mesc(r.meetingNo)}</td><td>${mesc(formatDate(r.meetingDate))}<div class="small">${mesc(r.meetingTime)}</div></td><td>${mesc(r.meetingType)}</td><td>${mesc(r.venue)}</td><td>${mesc(r.chairperson)}</td><td><span class="badge ${r.status==='Held'?'badge-green':r.status==='Postponed'?'badge-red':'badge-yellow'}">${mesc(r.status)}</span></td><td>${r.attachment?.url?`<a class="file-link" href="${mesc(r.attachment.url)}" target="_self">${mesc(r.attachment.name||'View')}</a>`:''}</td><td><div class="rg-grid-actions"><button class="rg-icon-btn rg-view" title="View meeting" aria-label="View meeting" onclick="selectMeeting('${mesc(r.id)}')">👁️ View</button><button class="rg-icon-btn rg-update" title="Update meeting" aria-label="Update meeting" onclick="selectMeeting('${mesc(r.id)}')">✏️</button><button class="rg-icon-btn rg-delete" title="Delete meeting" aria-label="Delete meeting" onclick="deleteMeetingById('${mesc(r.id)}')">🗑️</button></div></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No meetings found.</td></tr>';document.getElementById('meetingUpcoming').textContent=meetingRows.filter(r=>r.meetingDate>=today&&r.status==='To be held').length;document.getElementById('meetingHeld').textContent=meetingRows.filter(r=>r.status==='Held').length;document.getElementById('meetingPostponed').textContent=meetingRows.filter(r=>r.status==='Postponed').length;document.getElementById('meetingTotal').textContent=meetingRows.length;const f=document.getElementById('meetingActiveFilter');if(f){const key=specialUpcoming?'upcoming':specialHeld?'held':specialPostponed?'postponed':(dash?.filter==='__UPCOMING__'?'upcoming':'');const labels={upcoming:'Upcoming meetings only',held:'Held meetings only',postponed:'Postponed meetings only'};f.textContent=key?`Filter: ${labels[key]} — ${rows.length} record(s). Click Total to clear.`:'';f.style.display=key?'block':'none';}}
async function deleteMeetingById(id){const r=meetingRows.find(x=>String(x.id)===String(id));if(!r)return;if(!confirm(`Delete meeting ${r.meetingNo||""}?`))return;await RGMS.store.deleteRecord(STORAGE_KEYS.MEETINGS,id);await refreshMeetings();if(String(selectedMeetingId)===String(id))clearMeetingForm();mm("Meeting deleted.");}
window.deleteMeetingById=deleteMeetingById;
function selectMeeting(id){const r=meetingRows.find(x=>String(x.id)===String(id));if(!r)return;selectedMeetingId=r.id;document.getElementById('meetingDelete')?.removeAttribute('disabled');document.getElementById('meetingUpdate')?.removeAttribute('disabled');[['meetingNo',r.meetingNo],['meetingDate',r.meetingDate],['meetingTime',r.meetingTime],['meetingType',r.meetingType],['meetingStatus',r.status],['meetingVenue',r.venue],['meetingChair',r.chairperson],['meetingSecretary',r.secretary],['meetingQuorum',r.quorum],['meetingAgenda',r.agenda],['meetingAttendance',r.attendance],['meetingMinutes',r.minutes],['meetingActions',r.actionItems],['meetingNextDate',r.nextMeetingDate],['meetingLink',r.meetingLink]].forEach(([i,v])=>document.getElementById(i).value=v||'');mm('Meeting selected for editing.');}
function clearMeetingForm(){selectedMeetingId=null;document.getElementById('meetingDelete')?.setAttribute('disabled','disabled');document.getElementById('meetingUpdate')?.setAttribute('disabled','disabled');document.getElementById('meetingNo').value='';document.getElementById('meetingDate').value='';document.getElementById('meetingTime').value='16:30';document.getElementById('meetingType').value='General Body Meeting';document.getElementById('meetingStatus').value='To be held';document.getElementById('meetingVenue').value='Rose Gardens Colony';['meetingChair','meetingSecretary','meetingQuorum','meetingAgenda','meetingAttendance','meetingMinutes','meetingActions','meetingNextDate','meetingLink'].forEach(id=>document.getElementById(id).value='');document.getElementById('meetingFile').value='';}
function printMeeting(){const r=selectedMeetingId?meetingRows.find(x=>x.id===selectedMeetingId):mf();if(!r?.meetingDate)return mm('Select or save a meeting before printing.',true);const w=window.open('','_blank','width=900,height=700');w.document.write(`<html><head><title>${mesc(r.meetingNo)}</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccc;padding:8px;text-align:left;vertical-align:top}h1{color:#0b4f8a}</style></head><body><h1>Rose Gardens Residents Welfare Association</h1><h2>Meeting ${mesc(r.meetingNo||'')}</h2><table>${[['Date/Time',`${r.meetingDate} ${r.meetingTime||''}`],['Type',r.meetingType],['Status',r.status],['Venue',r.venue],['Chairperson',r.chairperson],['Secretary',r.secretary],['Quorum',r.quorum],['Agenda',r.agenda],['Attendance',r.attendance],['Minutes',r.minutes],['Action Items',r.actionItems],['Next Meeting',r.nextMeetingDate],['Meeting Link',r.meetingLink]].map(x=>`<tr><th>${mesc(x[0])}</th><td>${mesc(x[1])}</td></tr>`).join('')}</table><script>window.print()<\/script></body></html>`);w.document.close();}
function mm(t,e=false){const x=document.getElementById('meetingMessage');x.textContent=t;x.className='message '+(e?'error':'ok');}window.initializeMeetings=initializeMeetings;window.selectMeeting=selectMeeting;window.renderMeetings=renderMeetings;