let residentsRows=[]; let selectedResidentId=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').trim().toLowerCase();
const occupiedStatus=r=>{const occ=norm(r?.occupationStatus), status=norm(r?.status||r?.occupancyStatus); return occ!=='vacant' && status!=='vacant';};
function houseKey(r){return norm(r?.houseNo||r?.plotNo);}
function residentLabel(r){return r?.ownerName||r?.name||'Resident';}
async function initializeResidents(){

  await RGMS.store.refreshCollection(STORAGE_KEYS.RESIDENTS,{retries:2});
  // First-login initialization is now handled centrally by navigation, but the
  // module also self-heals a missing master if opened directly.
  if(!RGMS.store.getResidentMaster({includeVacant:true}).length){showResidentMessage('Unable to load latest Residents Master data from Firebase. Please try again.',true);}
  residentsRows=RGMS.store.getResidentMaster({includeVacant:true});
  bindResidentEvents(); renderResidents(); clearResidentForm();
}
function bindResidentEvents(){
  document.getElementById('resSave')?.addEventListener('click',saveResident);
  document.getElementById('resUpdate')?.addEventListener('click',updateSelectedResident);
  document.getElementById('resDelete')?.addEventListener('click',deleteResident);
  document.getElementById('resClear')?.addEventListener('click',clearResidentForm);
  document.getElementById('resRefresh')?.addEventListener('click',refreshResidents);
  document.getElementById('residentSearch')?.addEventListener('input',renderResidents);
  document.getElementById('residentsDashboardDetailClose')?.addEventListener('click',closeResidentsDetail);
  document.getElementById('residentsDashboardDetail')?.addEventListener('mouseleave',()=>{if(window.matchMedia('(hover:hover)').matches)closeResidentsDetail();});
  document.querySelectorAll('[data-residents-dashboard]').forEach(card=>{card.addEventListener('click',e=>{e.stopPropagation();drillResidents(card.dataset.residentsDashboard);});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();drillResidents(card.dataset.residentsDashboard);}});});
}
function residentForm(){const g=id=>document.getElementById(id);const occ=g('residentStatus')?.value||'Owner';const cell=g('mobile')?.value.trim()||'';return {residentId:g('residentId')?.value.trim()||'',plotNo:g('plotNo')?.value.trim()||'',houseNo:g('plotNo')?.value.trim()||'',ownerName:g('ownerName')?.value.trim()||'',name:g('ownerName')?.value.trim()||'',mobile:cell?[cell]:[],whatsapp:cell,residentType:g('residentType')?.value||'Owner',occupationStatus:occ,status:occ==='Vacant'?'Vacant':'Occupied',remarks:g('residentRemarks')?.value.trim()||'',role:'Resident'};}
function validateResident(r){if(!r.plotNo||!r.ownerName){showResidentMessage('H.No. and Name are required.',true);return false}return true;}
function normalizeResidentPayload(r,existing={}){const phone=normalizePhone(r.mobile?.[0]||r.whatsapp||'');const vacant=norm(r.occupationStatus)==='vacant';return {...existing,...r,houseNo:r.plotNo,plotNo:r.plotNo,name:r.ownerName,ownerName:r.ownerName,phoneE164:phone,isVacant:vacant,status:vacant?'Vacant':'Occupied',updatedOn:new Date().toISOString()};}
async function saveResident(){try{const r=residentForm();if(!validateResident(r))return;let id=selectedResidentId;
  // Allow multiple people at one H.No. (for Tenant / Family Member records),
  // while still preventing duplicate Owner records for the same H.No.
  const duplicateOwner=residentsRows.find(x=>String(x.id||x.residentId)!==String(id||'')&&houseKey(x)===norm(r.plotNo)&&norm(x.residentType)==='owner'&&norm(r.residentType)==='owner');
  if(duplicateOwner){showResidentMessage('An Owner record already exists for this H.No.',true);return;}
  if(id){const existing=residentsRows.find(x=>String(x.id||x.residentId)===String(id));const payload=normalizeResidentPayload(r,existing||{});await RGMS.store.setRecord(STORAGE_KEYS.RESIDENTS,id,payload);showResidentMessage('Resident updated successfully.');}
  else{r.residentId=`RGRWA-${String(Date.now()).slice(-8)}`;r.id=r.residentId;const payload=normalizeResidentPayload(r);payload.createdDate=new Date().toISOString().slice(0,10);payload.developmentFund=true;payload.festivalChanda=true;await RGMS.store.insertRecord(STORAGE_KEYS.RESIDENTS,payload);showResidentMessage('Resident saved successfully.');}
  await refreshResidents();clearResidentForm();
}catch(e){console.error(e);showResidentMessage(e?.message||'Unable to save resident.',true);}}

async function updateSelectedResident(){
  if(!selectedResidentId){showResidentMessage('Select a resident first.',true);return;}
  await saveResident();
}
async function deleteResident(){if(!selectedResidentId){showResidentMessage('Select a resident first.',true);return;}await deleteResidentById(selectedResidentId);}
async function deleteResidentById(id){const r=residentsRows.find(x=>String(x.id||x.residentId)===String(id));if(!r)return;if(!confirm(`Delete ${residentLabel(r)} (H.No. ${formatHNo(r.houseNo||r.plotNo)})?`))return;try{await RGMS.store.deleteRecord(STORAGE_KEYS.RESIDENTS,r.id||r.residentId);await refreshResidents();clearResidentForm();showResidentMessage('Resident deleted successfully.');}catch(e){console.error(e);showResidentMessage(e.message||'Unable to delete resident from Firebase.',true);}}
function selectResident(id){const r=residentsRows.find(x=>String(x.id||x.residentId)===String(id));if(!r)return;selectedResidentId=r.id||r.residentId;const vals={residentId:r.residentId||r.id,plotNo:r.houseNo||r.plotNo||'',ownerName:residentLabel(r),mobile:r.mobile?.[0]||r.whatsapp||'',residentType:r.residentType||'Owner',residentStatus:r.occupationStatus||r.status||'Owner',residentRemarks:r.remarks||''};Object.entries(vals).forEach(([k,v])=>{const el=document.getElementById(k);if(el)el.value=v;});const del=document.getElementById('resDelete');if(del)del.disabled=false;const upd=document.getElementById('resUpdate');if(upd)upd.disabled=false;showResidentMessage('Resident selected. Click Update to save changes.');document.querySelector('.residents-main-content .form-card')?.scrollIntoView({behavior:'smooth',block:'start'});}
function clearResidentForm(){selectedResidentId=null;const g=id=>document.getElementById(id);if(g('residentId'))g('residentId').value='';['plotNo','ownerName','mobile','residentRemarks'].forEach(id=>{if(g(id))g(id).value='';});if(g('residentType'))g('residentType').value='Owner';if(g('residentStatus'))g('residentStatus').value='Owner';if(g('resDelete'))g('resDelete').disabled=true;if(g('resUpdate'))g('resUpdate').disabled=true;}
async function refreshResidents(){await RGMS.store.refreshCollection(STORAGE_KEYS.RESIDENTS,{retries:2});residentsRows=RGMS.store.getResidentMaster({includeVacant:true});renderResidents();}
function renderResidents(){const q=norm(document.getElementById('residentSearch')?.value||'');const rows=residentsRows.filter(r=>[r.residentId,r.houseNo,r.plotNo,r.ownerName,r.name,r.whatsapp,r.mobile?.[0],r.occupationStatus,r.residentType,r.remarks].some(v=>norm(v).includes(q))).sort((a,b)=>String(a.ownerName||a.name||'').localeCompare(String(b.ownerName||b.name||''),undefined,{sensitivity:'base'}));document.getElementById('residentsBody').innerHTML=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(residentLabel(r))}</td><td>${esc(formatHNo(r.houseNo||r.plotNo))}</td><td>${esc(r.residentId||r.id||'')}</td><td>${esc(r.mobile?.[0]||r.whatsapp||'')}</td><td>${esc(r.residentType||'Owner')}</td><td>${esc(r.occupationStatus||r.status||'')}</td><td>${esc(r.remarks||'')}</td><td><div class="rg-grid-actions"><button class="rg-icon-btn rg-view" title="View / Edit" onclick="selectResident('${esc(r.id||r.residentId)}')">👁️ View</button><button class="rg-icon-btn rg-update" title="Edit" onclick="selectResident('${esc(r.id||r.residentId)}')">✏️</button><button class="rg-icon-btn rg-delete" title="Delete" onclick="deleteResidentById('${esc(r.id||r.residentId)}')">🗑️</button></div></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No residents found.</td></tr>';updateResidentSummary();}
function uniqueHouses(rows){return new Map(rows.map(r=>[houseKey(r),r])).size;}
function updateResidentSummary(){const total=uniqueHouses(residentsRows);const occupied=residentsRows.filter(occupiedStatus);const owner=occupied.filter(r=>norm(r.occupationStatus)==='owner');const tenant=occupied.filter(r=>norm(r.occupationStatus)==='tenant');const vacant=residentsRows.filter(r=>!occupiedStatus(r));document.getElementById('resTotal').textContent=total;document.getElementById('resOccupied').textContent=uniqueHouses(occupied);document.getElementById('resOwners').textContent=uniqueHouses(owner);document.getElementById('resTenants').textContent=uniqueHouses(tenant);document.getElementById('resVacant').textContent=uniqueHouses(vacant);}
function residentRowsForFilter(key){const occupied=residentsRows.filter(occupiedStatus);if(key==='total')return residentsRows;if(key==='occupied')return occupied;if(key==='owners')return occupied.filter(r=>norm(r.occupationStatus)==='owner');if(key==='tenants')return occupied.filter(r=>norm(r.occupationStatus)==='tenant');if(key==='vacant')return residentsRows.filter(r=>!occupiedStatus(r));return residentsRows;}
function drillResidents(key){const sec=document.getElementById('residentsDashboardDetail');if(!sec)return;if(sec.style.display==='block'&&sec.dataset.key===key){closeResidentsDetail();return;}const labels={total:'All Residents / Houses',occupied:'Occupied Houses',owners:'Occupied Owner Houses',tenants:'Occupied Tenant Houses',vacant:'Vacant Houses'};const rows=residentRowsForFilter(key).slice().sort((a,b)=>String(a.ownerName||a.name||'').localeCompare(String(b.ownerName||b.name||''),undefined,{sensitivity:'base'}));document.getElementById('residentsDashboardDetailTitle').textContent=labels[key]||'Filtered Residents';document.getElementById('residentsDashboardDetailHead').innerHTML='<tr><th>S.No.</th><th>Name</th><th>H.No.</th><th>Resident Type</th><th>Occupation Status</th><th>Mobile</th><th>Remarks</th></tr>';document.getElementById('residentsDashboardDetailBody').innerHTML=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(residentLabel(r))}</td><td>${esc(formatHNo(r.houseNo||r.plotNo))}</td><td>${esc(r.residentType||'Owner')}</td><td>${esc(r.occupationStatus||r.status||'')}</td><td>${esc(r.mobile?.[0]||r.whatsapp||'')}</td><td>${esc(r.remarks||'')}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No matching residents found.</td></tr>';sec.dataset.key=key;sec.style.display='block';sec.classList.add('dashboard-dropdown-open');document.getElementById('residentsManagementPage')?.classList.add('dashboard-drill-open');}
function closeResidentsDetail(){const sec=document.getElementById('residentsDashboardDetail');if(sec){sec.style.display='none';sec.classList.remove('dashboard-dropdown-open');delete sec.dataset.key;}document.getElementById('residentsManagementPage')?.classList.remove('dashboard-drill-open');}
function showResidentMessage(t,error=false){const e=document.getElementById('resMessage');if(e){e.textContent=t;e.className='message '+(error?'error':'ok');}}
window.initializeResidents=initializeResidents;window.selectResident=selectResident;window.deleteResidentById=deleteResidentById;window.closeResidentsDetail=closeResidentsDetail;
