let visitorRows=[];let selectedVisitorId=null;let visitorDashboardFilter="";const vesc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function initializeVisitors(){await RGMS.store.loadCollection(STORAGE_KEYS.VISITORS);visitorRows=getAllRecords(STORAGE_KEYS.VISITORS);populateVisitorResidents();bindVisitorEvents();renderVisitors();clearVisitorForm();}
function bindVisitorEvents(){const m={visitorSave:saveVisitor,visitorUpdate:updateVisitor,visitorDelete:deleteVisitor,visitorClear:clearVisitorForm,visitorRefresh:refreshVisitors};Object.entries(m).forEach(([id,fn])=>document.getElementById(id)?.addEventListener('click',fn));document.getElementById('visitorSearch')?.addEventListener('input',renderVisitors);document.getElementById('visitorPlot')?.addEventListener('change',syncVisitorHouse);document.querySelectorAll('[data-visitor-dashboard]').forEach(c=>{const run=()=>{visitorDashboardFilter=c.dataset.visitorDashboard||'';renderVisitors();};c.addEventListener('click',run);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run();}});});}
function visitorResidents(){return RGMS.store.getResidentMaster({includeVacant:true}).filter(r=>String(r.status||r.occupationStatus||'').toLowerCase()!=='vacant').sort((a,b)=>String(a.ownerName||a.name||'').localeCompare(String(b.ownerName||b.name||''),'en',{sensitivity:'base',numeric:true}));}
function visitorResidentKey(r){return String(r.residentDocId||r.id||r.residentId||`${r.houseNo||r.plotNo||''}|${r.residentType||''}|${r.ownerName||r.name||''}`);}
function selectedVisitorResident(){const key=String(document.getElementById('visitorPlot')?.value||'');return visitorResidents().find(r=>visitorResidentKey(r)===key)||null;}
function populateVisitorResidents(){const s=document.getElementById('visitorPlot');if(!s)return;const current=s.value;s.innerHTML='<option value="">Select Name</option>'+visitorResidents().map(r=>`<option value="${vesc(visitorResidentKey(r))}">${vesc(r.ownerName||r.name||'Resident')}</option>`).join('');if(current)s.value=current;syncVisitorHouse();}
if(!window.__rgVisitorResidentSync){window.__rgVisitorResidentSync=true;window.addEventListener('rgms:resident-directory-changed',()=>{try{populateVisitorResidents();}catch(e){console.warn('Visitor resident dropdown refresh failed',e);}});}
function syncVisitorHouse(){const r=selectedVisitorResident();const h=document.getElementById('visitorHouse');if(h)h.value=r?formatHNo(r.houseNo||r.plotNo||''):'';}
function vf(){const resident=selectedVisitorResident();return {visitDate:document.getElementById('visitDate').value,visitorName:document.getElementById('visitorName').value.trim(),visitorMobile:document.getElementById('visitorMobile').value.trim(),residentId:resident?.residentId||resident?.id||'',plotNo:resident?.plotNo||resident?.houseNo||'',houseNo:resident?.houseNo||resident?.plotNo||'',residentName:resident?.ownerName||resident?.name||'',purpose:document.getElementById('visitorPurpose').value,vehicleNo:document.getElementById('visitorVehicle').value.trim(),persons:Number(document.getElementById('visitorPersons').value||1),entryTime:document.getElementById('visitorEntry').value,exitTime:document.getElementById('visitorExit').value,remarks:document.getElementById('visitorRemarks').value.trim()};}
async function saveVisitor(){if(selectedVisitorId){await updateVisitor();return;}const r=vf();if(!r.visitDate||!r.visitorName||!r.plotNo)return vm('Visit date, Visitor Name and Resident are required.',true);const rec={...r,phoneE164:normalizePhone(r.visitorMobile),createdOn:new Date().toISOString(),registeredBy:RGMS.auth.getSession()?.email||''};await insertRecord(STORAGE_KEYS.VISITORS,rec);await refreshVisitors();vm('Visitor registered successfully.');clearVisitorForm();}
async function updateVisitor(){if(!selectedVisitorId)return vm('Select a visitor record first.',true);const r=vf();if(!r.visitDate||!r.visitorName||!r.plotNo)return vm('Visit date, Visitor Name and Resident are required.',true);await RGMS.store.setRecord(STORAGE_KEYS.VISITORS,selectedVisitorId,{...r,phoneE164:normalizePhone(r.visitorMobile),updatedOn:new Date().toISOString()});await refreshVisitors();vm('Visitor updated.');clearVisitorForm();}
async function deleteVisitor(){if(!selectedVisitorId)return vm('Select a visitor record first.',true);if(!confirm('Delete this visitor record?'))return;await RGMS.store.deleteRecord(STORAGE_KEYS.VISITORS,selectedVisitorId);await refreshVisitors();vm('Visitor deleted.');clearVisitorForm();}
async function refreshVisitors(){await RGMS.store.refreshCollection(STORAGE_KEYS.VISITORS,{retries:2});visitorRows=getAllRecords(STORAGE_KEYS.VISITORS);renderVisitors();}
function renderVisitors(){const q=(document.getElementById('visitorSearch')?.value||'').toLowerCase();const dash=window.RGMS?.consumeDashboardFilter?.('visitors');if(dash?.filter==='__TODAY__')visitorDashboardFilter='today';const today=new Date().toISOString().slice(0,10);const matchDash=r=>!visitorDashboardFilter||visitorDashboardFilter==='total'||(visitorDashboardFilter==='today'&&r.visitDate===today)||(visitorDashboardFilter==='in'&&r.visitDate===today&&!r.exitTime);const rows=visitorRows.filter(r=>matchDash(r)&&[r.visitorName,r.residentName,r.plotNo,r.purpose,r.vehicleNo].some(v=>String(v||'').toLowerCase().includes(q))).sort((a,b)=>String(a.residentName||'').localeCompare(String(b.residentName||''),'en',{sensitivity:'base',numeric:true})||String(a.houseNo||a.plotNo||'').localeCompare(String(b.houseNo||b.plotNo||''),undefined,{numeric:true}));document.getElementById('visitorsBody').innerHTML=rows.map((r,i)=>`<tr><td>${i+1}</td><td>${vesc(r.residentName||'')}</td><td>${vesc(formatHNo(r.houseNo||r.plotNo))}</td><td>${vesc(formatDate(r.visitDate))}</td><td>${vesc(r.visitorName)}<div class="small">${vesc(r.visitorMobile)}</div></td><td>${vesc(r.purpose)}</td><td>${vesc(r.vehicleNo)}</td><td>${vesc(r.entryTime)}</td><td>${vesc(r.exitTime||'In')}</td><td><div class="rg-grid-actions"><button class="rg-icon-btn rg-view" title="View visitor" aria-label="View visitor" onclick="selectVisitor('${vesc(r.id)}')">👁️ View</button><button class="rg-icon-btn rg-update" title="Update visitor" aria-label="Update visitor" onclick="selectVisitor('${vesc(r.id)}')">✏️ Edit</button><button class="rg-icon-btn rg-delete" title="Delete visitor" aria-label="Delete visitor" onclick="deleteVisitorById('${vesc(r.id)}')">🗑️ Delete</button></div></td></tr>`).join('')||'<tr><td colspan="10" class="empty">No visitor records found for this filter.</td></tr>';document.getElementById('visitorToday').textContent=visitorRows.filter(r=>r.visitDate===today).length;document.getElementById('visitorIn').textContent=visitorRows.filter(r=>r.visitDate===today&&!r.exitTime).length;document.getElementById('visitorTotal').textContent=visitorRows.length;const f=document.getElementById('visitorActiveFilter');if(f){const labels={total:'All visitor records',today:"Today's visitors only",in:'Visitors currently in only'};f.textContent=visitorDashboardFilter?`Filter: ${labels[visitorDashboardFilter]} — ${rows.length} record(s). Click Total Records to clear.`:'';f.style.display=visitorDashboardFilter?'block':'none';}}
async function deleteVisitorById(id){const r=visitorRows.find(x=>String(x.id)===String(id));if(!r)return;if(!confirm(`Delete visitor ${r.visitorName||""}?`))return;await RGMS.store.deleteRecord(STORAGE_KEYS.VISITORS,id);await refreshVisitors();if(String(selectedVisitorId)===String(id))clearVisitorForm();vm("Visitor deleted.");}
window.deleteVisitorById=deleteVisitorById;
function selectVisitor(id){const r=visitorRows.find(x=>String(x.id)===String(id));if(!r)return;selectedVisitorId=r.id;const match=visitorResidents().find(x=>(r.residentId&&String(x.residentId||x.id)===String(r.residentId))||(!r.residentId&&String(x.houseNo||x.plotNo)===String(r.houseNo||r.plotNo)&&String(x.ownerName||x.name||'').toLowerCase()===String(r.residentName||'').toLowerCase()));[['visitDate',r.visitDate],['visitorName',r.visitorName],['visitorMobile',r.visitorMobile],['visitorPurpose',r.purpose||'Personal Visit'],['visitorVehicle',r.vehicleNo],['visitorPersons',r.persons||1],['visitorEntry',r.entryTime],['visitorExit',r.exitTime],['visitorRemarks',r.remarks]].forEach(([i,v])=>document.getElementById(i).value=v||'');document.getElementById('visitorPlot').value=match?visitorResidentKey(match):'';syncVisitorHouse();vm('Visitor selected for editing.');}
function clearVisitorForm(){selectedVisitorId=null;document.getElementById('visitDate').value=new Date().toISOString().slice(0,10);document.getElementById('visitorName').value='';document.getElementById('visitorMobile').value='';document.getElementById('visitorPlot').value='';if(document.getElementById('visitorHouse'))document.getElementById('visitorHouse').value='';document.getElementById('visitorPurpose').value='Personal Visit';document.getElementById('visitorVehicle').value='';document.getElementById('visitorPersons').value='1';document.getElementById('visitorEntry').value=new Date().toTimeString().slice(0,5);document.getElementById('visitorExit').value='';document.getElementById('visitorRemarks').value='';}
function vm(t,e=false){const x=document.getElementById('visitorMessage');x.textContent=t;x.className='message '+(e?'error':'ok');}window.initializeVisitors=initializeVisitors;window.selectVisitor=selectVisitor;