/* =========================================================
   FMS CENTRAL WHATSAPP SERVICE
   Version 4.0
   User-selectable delivery: device share chooser, WhatsApp/Business app,
   WhatsApp Web, universal wa.me, or configured Cloud API.
========================================================= */
(function(window, document){
  "use strict";
  const MAX_MESSAGE_LENGTH=4000; let modal=null;
  function esc(v){return String(v??"").trim();} function normalizePhone(v){return String(v||"").replace(/[^0-9]/g,"");}
  function firebaseFunctions(){try{if(window.getFMSFunctions)return window.getFMSFunctions();if(window.firebase?.functions)return window.firebase.functions("asia-south1");}catch(_e){}return null;}
  function defaultMessage(module,options){const title=esc(options.title||`${module} update`),date=new Date().toLocaleDateString("en-IN"),summary=esc(options.summaryText||"");return `${title}\nModule: ${module}\nStatus as on: ${date}\n\n${summary?summary+"\n\n":""}Please type your message here.`;}
  function ensureModal(){
    if(modal)return modal; const wrap=document.createElement("div");wrap.id="fmsWhatsAppModal";wrap.innerHTML=`
      <div class="fms-wa-backdrop"></div><div class="fms-wa-dialog" role="dialog" aria-modal="true" aria-labelledby="fmsWaTitle">
      <div class="fms-wa-header"><strong id="fmsWaTitle"><i class="bi bi-whatsapp"></i> WhatsApp Share / Send</strong><button type="button" id="fmsWaClose" aria-label="Close">&times;</button></div>
      <div class="fms-wa-body">
        <div class="row g-2"><div class="col-md-5"><label class="form-label fw-semibold">Module</label><input id="fmsWaModule" class="form-control" readonly></div>
        <div class="col-md-7"><label class="form-label fw-semibold">Open / Send Using</label><select id="fmsWaMethod" class="form-select">
          <option value="chooser">Device Share Menu — choose WhatsApp / WhatsApp Business</option>
          <option value="app">WhatsApp App / WhatsApp Business App</option>
          <option value="web">WhatsApp Web</option>
          <option value="universal">WhatsApp Universal (wa.me)</option>
          <option value="cloud">WhatsApp Cloud API — direct send</option>
        </select></div></div>
        <div class="mt-2"><label class="form-label fw-semibold">Recipient WhatsApp Number <span id="fmsWaPhoneHint" class="fw-normal text-muted">(optional for share menu)</span></label><input id="fmsWaRecipient" class="form-control" inputmode="numeric" placeholder="9198XXXXXXXX" maxlength="20"><div class="form-text">For a specific recipient use international format without + or spaces.</div></div>
        <div class="mt-2"><label class="form-label fw-semibold">Custom Message</label><textarea id="fmsWaMessage" class="form-control" rows="9" maxlength="4000"></textarea><div class="form-text text-end"><span id="fmsWaCount">0</span>/4000</div></div>
        <div id="fmsWaInfo" class="alert alert-info py-2 small mt-2 mb-0"></div><div id="fmsWaStatus" class="mt-2 small"></div>
      </div><div class="fms-wa-footer"><button type="button" class="btn btn-secondary" id="fmsWaCancel">Cancel</button><button type="button" class="btn btn-success" id="fmsWaSend"><i class="bi bi-whatsapp"></i> Continue</button></div></div>`;
    const style=document.createElement("style");style.textContent=`#fmsWhatsAppModal{position:fixed;inset:0;z-index:99999;display:none}.fms-wa-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.55)}.fms-wa-dialog{position:relative;width:min(720px,calc(100% - 28px));max-height:94vh;overflow:auto;margin:3vh auto;background:#fff;border-radius:12px;box-shadow:0 12px 40px rgba(0,0,0,.3)}.fms-wa-header{display:flex;justify-content:space-between;align-items:center;padding:14px 18px;border-bottom:1px solid #ddd}.fms-wa-header button{border:0;background:transparent;font-size:28px;line-height:1}.fms-wa-body{padding:18px}.fms-wa-footer{display:flex;justify-content:flex-end;gap:8px;padding:12px 18px;border-top:1px solid #ddd}`;document.head.appendChild(style);document.body.appendChild(wrap);modal=wrap;
    const close=()=>wrap.style.display="none";wrap.querySelector("#fmsWaClose").onclick=close;wrap.querySelector("#fmsWaCancel").onclick=close;wrap.querySelector(".fms-wa-backdrop").onclick=close;wrap.querySelector("#fmsWaMessage").addEventListener("input",()=>wrap.querySelector("#fmsWaCount").textContent=wrap.querySelector("#fmsWaMessage").value.length);wrap.querySelector("#fmsWaMethod").onchange=updateMethodHelp;updateMethodHelp();return wrap;
  }
  function updateMethodHelp(){const el=modal||document.getElementById("fmsWhatsAppModal");if(!el)return;const method=el.querySelector("#fmsWaMethod").value,info=el.querySelector("#fmsWaInfo"),hint=el.querySelector("#fmsWaPhoneHint"),send=el.querySelector("#fmsWaSend");const help={chooser:"Opens your device share menu. On supported phones/tablets you can select WhatsApp, WhatsApp Business, or another installed app.",app:"Uses the WhatsApp app link. If your device has more than one compatible WhatsApp app, the operating system may ask which app to use.",web:"Opens WhatsApp Web in the browser with the prepared message.",universal:"Uses the official wa.me universal link. The device/browser decides whether to open the app or web experience.",cloud:"Sends directly through the configured WhatsApp Cloud API. A recipient number is required and Meta messaging rules apply."};info.textContent=help[method]||"";hint.textContent=method==="cloud"?"(required for Cloud API)":"(optional unless sending to a specific person)";send.innerHTML=method==="cloud"?'<i class="bi bi-send"></i> Send Directly':'<i class="bi bi-box-arrow-up-right"></i> Open / Share';}
  async function sendCustomMessage({module,recipient,message}){const to=normalizePhone(recipient),text=esc(message);if(to.length<8||to.length>15)throw new Error("Enter a valid international WhatsApp number, e.g. 9198XXXXXXXX.");if(!text)throw new Error("Please enter a message.");if(text.length>MAX_MESSAGE_LENGTH)throw new Error("Message is too long. Maximum 4000 characters.");const fn=firebaseFunctions();if(!fn)throw new Error("Firebase Functions client is not loaded. Please refresh the page.");const callable=fn.httpsCallable("sendCustomWhatsAppMessage");const result=await callable({module:esc(module||"FMS"),to,message:text});return result.data||{success:true};}
  function validateExternalPhone(phone){const p=normalizePhone(phone);if(p&&(p.length<8||p.length>15))throw new Error("Enter a valid international WhatsApp number, or leave it blank to choose a recipient later.");return p;}
  function openUrl(url){const w=window.open(url,"_blank","noopener,noreferrer");if(!w)window.location.href=url;}
  async function dispatch(method,{module,recipient,message}){const text=esc(message);if(!text)throw new Error("Please enter a message.");if(text.length>MAX_MESSAGE_LENGTH)throw new Error("Message is too long. Maximum 4000 characters.");if(method==="cloud")return sendCustomMessage({module,recipient,message:text});const phone=validateExternalPhone(recipient),q=encodeURIComponent(text);
    if(method==="chooser"){if(navigator.share){await navigator.share({title:`${module} - FMS`,text});return {success:true,method:"share-menu"};}method="universal";}
    if(method==="app"){openUrl(`whatsapp://send?${phone?`phone=${phone}&`:""}text=${q}`);return {success:true,method};}
    if(method==="web"){openUrl(`https://web.whatsapp.com/send?${phone?`phone=${phone}&`:""}text=${q}`);return {success:true,method};}
    openUrl(phone?`https://wa.me/${phone}?text=${q}`:`https://wa.me/?text=${q}`);return {success:true,method:"universal"};
  }
  async function compose(options={}){const module=esc(options.module||"FMS").toUpperCase(),el=ensureModal();el.querySelector("#fmsWaModule").value=module;el.querySelector("#fmsWaRecipient").value=esc(options.recipient||"");el.querySelector("#fmsWaMessage").value=esc(options.defaultMessage||defaultMessage(module,options));el.querySelector("#fmsWaCount").textContent=el.querySelector("#fmsWaMessage").value.length;el.querySelector("#fmsWaStatus").textContent="";el.querySelector("#fmsWaMethod").value=options.method||"chooser";updateMethodHelp();el.style.display="block";const send=el.querySelector("#fmsWaSend");send.onclick=async()=>{const status=el.querySelector("#fmsWaStatus"),method=el.querySelector("#fmsWaMethod").value;send.disabled=true;status.className="mt-2 small text-muted";status.textContent=method==="cloud"?"Sending...":"Opening selected WhatsApp option...";try{await dispatch(method,{module,recipient:el.querySelector("#fmsWaRecipient").value,message:el.querySelector("#fmsWaMessage").value});status.className="mt-2 small text-success fw-semibold";status.textContent=method==="cloud"?"WhatsApp message sent successfully.":"WhatsApp option opened. Complete the send in the selected app/window.";if(typeof options.message==="function")options.message(status.textContent,"success");if(method!=="cloud")setTimeout(()=>{el.style.display="none";},500);}catch(e){if(e?.name==="AbortError"){status.textContent="Share cancelled.";}else{console.error("WhatsApp action failed:",e);status.className="mt-2 small text-danger";status.textContent=e?.message||"Unable to open/send WhatsApp.";if(typeof options.message==="function")options.message(status.textContent,"danger");}}finally{send.disabled=false;updateMethodHelp();}};return {success:true,method:"selectable-composer",module};}
  function openWhatsApp(text){openUrl("https://wa.me/?text="+encodeURIComponent(text||""));}
  window.FMSWhatsAppService={compose,sendCustomMessage,dispatch,openWhatsApp};
})(window,document);
