/* =========================================================
   FMS CENTRAL WHATSAPP SERVICE
   Version 1.0
   Purpose: Share reports and dashboard/form snapshots across modules.
   Lekha Technologies
========================================================= */
(function(window, document){
    "use strict";

    const CDN = "https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js";

    function esc(value){
        return String(value ?? "").trim();
    }

    function getValue(id){
        const el = document.getElementById(id);
        if(!el) return "";
        if(el.tagName === "SELECT"){
            const opt = el.options[el.selectedIndex];
            return opt ? (opt.text || el.value || "") : "";
        }
        return el.value || el.textContent || "";
    }

    function loadHtml2Canvas(){
        if(window.html2canvas) return Promise.resolve(window.html2canvas);
        if(window.__fmsHtml2CanvasPromise) return window.__fmsHtml2CanvasPromise;
        window.__fmsHtml2CanvasPromise = new Promise((resolve,reject)=>{
            const s=document.createElement("script");
            s.src=CDN;
            s.onload=()=>resolve(window.html2canvas);
            s.onerror=()=>reject(new Error("Dashboard image service could not be loaded."));
            document.head.appendChild(s);
        });
        return window.__fmsHtml2CanvasPromise;
    }

    function openWhatsApp(text){
        const url = "https://wa.me/?text=" + encodeURIComponent(text || "");
        window.open(url, "_blank", "noopener,noreferrer");
    }

    function downloadBlob(blob, name){
        const url=URL.createObjectURL(blob);
        const a=document.createElement("a");
        a.href=url; a.download=name;
        document.body.appendChild(a); a.click(); a.remove();
        setTimeout(()=>URL.revokeObjectURL(url),1000);
    }

    async function capture(element){
        if(!element) return null;
        const h2c=await loadHtml2Canvas();
        const canvas=await h2c(element,{
            scale: Math.min(2, window.devicePixelRatio || 1.5),
            useCORS:true,
            backgroundColor:"#ffffff",
            logging:false
        });
        return await new Promise(resolve=>canvas.toBlob(resolve,"image/png",0.95));
    }

    async function copyImage(blob){
        try{
            if(!navigator.clipboard || !window.ClipboardItem) return false;
            await navigator.clipboard.write([
                new ClipboardItem({"image/png":blob})
            ]);
            return true;
        }catch(e){
            console.warn("Image clipboard copy unavailable:",e);
            return false;
        }
    }

    function defaultTarget(){
        return document.querySelector("#dashboardContent") ||
               document.querySelector(".dashboard-container") ||
               document.querySelector(".status-card")?.parentElement?.parentElement ||
               document.querySelector("main") ||
               document.querySelector(".container-fluid") ||
               document.body;
    }

    async function share(options={}){
        const title=esc(options.title || "FMS Report");
        const module=esc(options.module || "FMS");
        const lines=[`*${title}*`,`*Module:* ${module}`,""];

        (options.fields || []).forEach(item=>{
            const value=esc(getValue(item.id));
            if(value) lines.push(`*${item.label}:* ${value}`);
        });

        if(options.extraText) lines.push("", esc(options.extraText));
        lines.push("",`Generated by FMS | ${new Date().toLocaleString("en-IN")}`);
        const text=lines.join("\n");

        let imageBlob=null;
        let copied=false;
        try{
            imageBlob=await capture(options.element || defaultTarget());
        }catch(e){
            console.warn("Dashboard/form image capture skipped:",e);
        }

        if(imageBlob && navigator.share && navigator.canShare){
            try{
                const file=new File([imageBlob],`${module.replace(/\s+/g,"_")}_Report.png`,{type:"image/png"});
                if(navigator.canShare({files:[file]})){
                    await navigator.share({title,text,files:[file]});
                    return {success:true,method:"native-share",image:true};
                }
            }catch(e){
                if(e && e.name==="AbortError") return {success:false,cancelled:true};
                console.warn("Native share failed:",e);
            }
        }

        if(imageBlob) copied=await copyImage(imageBlob);
        openWhatsApp(text);

        if(options.message){
            options.message(
                copied
                  ? "WhatsApp opened with the report text. The dashboard/report image was copied to your clipboard; paste it into the WhatsApp chat."
                  : "WhatsApp opened with the report text. Your browser does not allow direct image sharing here."
            );
        }
        return {success:true,method:"whatsapp-text",imageCopied:copied};
    }

    async function shareDashboard(options={}){
        const element=options.element || defaultTarget();
        return share({
            ...options,
            title:options.title || "FMS Dashboard Report",
            module:options.module || "FMS",
            element
        });
    }


    function collectCardNumbers() {
        const selectors = [
            ".summary-card", ".stat-card", ".dashboard-card",
            ".metric-card", ".status-card", ".kpi-card",
            "[data-dashboard-card]"
        ];
        const seen = new Set();
        const cards = [];
        selectors.forEach(sel => document.querySelectorAll(sel).forEach(card => {
            if (seen.has(card)) return;
            seen.add(card);
            const text = esc(card.innerText || "");
            if (!text) return;
            // Keep cards that contain at least one number.
            if (/\d/.test(text)) cards.push(text.replace(/\s+/g, " ").trim());
        }));
        return cards;
    }

    function collectTableSummary(element) {
        const table = element?.querySelector?.("table") ||
                      (element?.tagName === "TABLE" ? element : null) ||
                      document.querySelector("#dailyStatusTable") ||
                      document.querySelector("#registerTable") ||
                      document.querySelector("table");
        if (!table) return [];
        return Array.from(table.querySelectorAll("tr")).map(tr =>
            Array.from(tr.querySelectorAll("th,td"))
                .map(c => esc(c.innerText).replace(/\s+/g, " "))
                .filter(Boolean)
                .join(" | ")
        ).filter(Boolean);
    }

    function parseDateValue(value){
        if(!value) return null;
        if(value && typeof value.toDate==="function") return value.toDate();
        if(value && value.seconds!==undefined) return new Date(Number(value.seconds)*1000);
        if(value && value._seconds!==undefined) return new Date(Number(value._seconds)*1000);
        if(value instanceof Date) return value;
        const s=String(value).trim();
        let m=s.match(/^(\d{2})[\/-](\d{2})[\/-](\d{4})$/);
        if(m) return new Date(Number(m[3]),Number(m[2])-1,Number(m[1]));
        m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);
        if(m) return new Date(Number(m[1]),Number(m[2])-1,Number(m[3]));
        const d=new Date(s);
        return Number.isNaN(d.getTime()) ? null : d;
    }

    function fmtDate(value){
        const d=parseDateValue(value);
        return d ? `${d.getDate().toString().padStart(2,"0")}/${(d.getMonth()+1).toString().padStart(2,"0")}/${d.getFullYear()}` : esc(value);
    }

    function fmtDateNoPad(value){
        const d=parseDateValue(value);
        return d ? `${d.getDate()}/${d.getMonth()+1}/${d.getFullYear()}` : esc(value);
    }

    function currentFY(){
        const d=new Date(), y=d.getFullYear(), m=d.getMonth()+1;
        return m>=4 ? `${y}-${String(y+1).slice(-2)}` : `${y-1}-${String(y).slice(-2)}`;
    }

    function inFY(value, fy){
        const d=parseDateValue(value); if(!d) return false;
        const y=Number(String(fy).slice(0,4));
        const start=new Date(y,3,1); start.setHours(0,0,0,0);
        const end=new Date(y+1,2,31,23,59,59,999);
        return d>=start && d<=end;
    }

    function val(row, keys){
        for(const k of keys){
            const v=row?.[k];
            if(v!==undefined && v!==null && String(v).trim()!=="") return v;
        }
        return "";
    }

    async function getCollectionRows(collection){
        const database = window.getFMSFirestore ? window.getFMSFirestore() :
                         window.fmsFirebase?.db || window.db ||
                         (typeof db!=="undefined" ? db : null);
        if(!database) throw new Error("Firebase Firestore is not available.");
        const snap=await database.collection(collection).get();
        return snap.docs.map(d=>({id:d.id,...d.data()}));
    }

    function buildCPGRAMSWhatsApp(rows, fy){
        const header=[
            "*CPGRAMS Daily Status Report*",
            `*Financial Year:* ${fy}`,
            `*Status as on:* ${fmtDateNoPad(new Date())}`,
            "",
            "Sl.No | Grievance Number | Date Received | Complainant Name | District | Subject | Current Status | Due Date | Action"
        ];
        rows.forEach((r,i)=>{
            const status=val(r,["currentStatus","presentStatus","statusOfFile","officeStatus","status"]);
            const action=val(r,["action","remarks","lastAction","disposalAction"]);
            header.push([
                i+1,
                val(r,["grievanceNumber","grievanceNo","applicationNumber"]),
                fmtDate(val(r,["dateReceived","receivedDate"])),
                val(r,["complainantName","applicantName"]),
                val(r,["district"]),
                val(r,["subject","grievanceDescription"]),
                status,
                fmtDate(val(r,["dueDate"])),
                action
            ].join(" | "));
        });
        return header.join("\n");
    }

    function buildRTIWhatsApp(rows){
        const header=[
            "*RTI Daily Status Report*",
            `*Status as on:* ${fmtDateNoPad(new Date())}`,
            "",
            "Sl.No. | Name of the Applicant | Date | Information Requested | Concerned Officer | Status"
        ];
        rows.forEach((r,i)=>{
            header.push([
                i+1,
                val(r,["applicantName","nameOfApplicant","name"]),
                fmtDate(val(r,["applicationDate","date"])),
                val(r,["informationSought","informationRequested","informationRequestedText"]),
                val(r,["concernedOfficer","assignedTo","officer","letterAddressedTo","replyObtainedFrom"]),
                val(r,["currentStatus","presentStatus","statusOfFile","officeStatus","status"])
            ].join(" | "));
        });
        return header.join("\n");
    }

    function buildDISHAWhatsApp(rows){
        const today=new Date(); today.setHours(0,0,0,0);
        const header=[
            "*DISHA Meetings Daily Status Report*",
            `*Status as on:* ${fmtDate(new Date())}`,
            "",
            "Sl.No | Name of the District | Date of Meeting | Status of Meeting | PoM Uploaded | No. of days left for PoM upload | No. of days pending for PoM Upload"
        ];
        rows.forEach((r,i)=>{
            const meeting=val(r,["dateOfMeeting","meetingDate"]);
            const due=val(r,["pomDueDate","dueDate"]);
            const d=parseDateValue(due);
            const uploaded=val(r,["pomUploaded","pomStatus"]) || "No";
            let left="", pending="";
            if(d){
                d.setHours(0,0,0,0);
                const diff=Math.round((d-today)/86400000);
                if(diff>=0) left=diff;
                else pending=Math.abs(diff);
            }
            header.push([
                i+1,
                val(r,["district","nameOfDistrict"]),
                fmtDate(meeting),
                val(r,["statusOfMeeting","meetingStatus","status"]),
                uploaded,
                left,
                pending
            ].join(" | "));
        });
        return header.join("\n");
    }

    async function shareDailyStatus(options={}){
        const module=esc(options.module||"FMS").toUpperCase();
        let text="";
        const fy=currentFY();

        if(module==="CPGRAMS"){
            let rows=await getCollectionRows("cpgrams");
            rows=rows.filter(r=>inFY(val(r,["dateReceived","receivedDate","dateArised"]),fy));
            text=buildCPGRAMSWhatsApp(rows,fy);
        }else if(module==="RTI"){
            let rows=await getCollectionRows("rtiApplications");
            rows=rows.filter(r=>inFY(val(r,["applicationDate","date"]),fy));
            text=buildRTIWhatsApp(rows);
        }else if(module==="DISHA"){
            let rows=await getCollectionRows("dishaMeetings");
            rows=rows.filter(r=>inFY(val(r,["dateOfMeeting","meetingDate"]),fy));
            text=buildDISHAWhatsApp(rows);
        }else{
            const title=esc(options.title||`${module} Daily Status Report`);
            const element=options.element||document.querySelector("#dailyStatusTable")||document.querySelector("#registerTable")||document.querySelector("main")||document.body;
            const lines=[`*${title}*`,`*Module:* ${module}`,`*Status as on:* ${fmtDate(new Date())}`,""];
            if(options.summaryText) lines.push(String(options.summaryText).trim(),"");
            const rows=collectTableSummary(element);
            lines.push(...rows);
            text=lines.join("\n");
        }

        // Text-only WhatsApp: no Excel export, no image, no attachment.
        openWhatsApp(text);
        if(options.message) options.message("WhatsApp opened with the Daily Status report as a text message. No Excel file is exported.");
        return {success:true,method:"whatsapp-text",excelExported:false,text};
    }

    window.FMSWhatsAppService={share,shareDashboard,shareDailyStatus,openWhatsApp,capture};
})(window,document);
